export var menu_title = {
    create_order: "Створити замовлення",
    upload_document: "Загрузити документ",
    order: "Замовлення",
    deliveries: "Доставки",
    history: "Історія",
    product: "Категорія",
    item: "Продукт",
    setting: "Налаштування",
    earning: "Заробіток",
    sub_earning: "Заробіток",
    sub_daily_earning: "Денний заробіток",
    sub_weekly_earning: "Тижневий заробіток",
    profile: "Профіль",
    logout: "Вийти",
    promocode: "Промокод",
    menu: 'Меню',
    providers: 'Кур\’єри',
    delivery_prices: 'Вартості доставки'
}

export var title = {
    select_vehicle: 'Обрати транспортний засіб',
    vat: 'НДС(%)',
    is_use_item_tax: 'Податок на використання',
    enter_modifier_group_name: 'Введіть назву групи модифікатора',
    product_price: 'Вартість категорії',
    admin_email: 'Електронна пошта адміністратора',
    admin_phone: 'Номер телефону адміністратора',
    order_start_at: 'Замовлення починається з',
    asap: 'Якнайшвидше',
    km:"км",
    is_store_can_add_provider: 'Заклад може додати кур\’єра',
    is_store_can_set_delivery_prices: 'Заклад може встановлювати вартості доставки',
    is_store_can_complete_order: 'Заклад може завершувати замовлення',
    schedule: 'Передзамовлення',
    deliveryman: 'Кур\’єр',
    created_by: 'Створений',
    ///////////////for store Register //////////////////////////
    language:"Мова",
    is_ask_estimated_time_for_ready_order: "Назначте кур\’єру, коли замовлення буде прийняте",
    name: "Назва",
    email: "Електронна пошта",
    password: "Пароль",
    confirm_password:"Підтвердити пароль",
    website_url: "Url вебсайту",
    slogan: "Лозунг",
    select_country : "Обрати країну",
    select_city: "Обрати місто",
    address: "Адреса",
    country_phone_code: "Код телефону",
    phone: "Номер телефону",
    fax_number: "Номер факсу",
    select_delivery: "Обрати тип доставки",
    latitude: "Широта",
    longitude: "Довгота",
    famous_for: "Відомий для",
    image_url: "Зображення",
    referral_code: "Реферальний код",
    message_602:"готово",
is_required:"Обов\’язково",
    delivery_time:"Мінімальний час доставки",
    delivery_time_max:"Максимальний час доставки",

    register_your_account:"Зареєструйте свій акаунт",
    confirmation_code:"Код підтвердження",
    sms_otp: "Код верифікації SMS",
    email_otp: "Код верифікації електронної пошти",
    verification:"Верифікація",
    spec: "Спец.",
promo_expiry_date: 'Строк дії',
product: 'Категорія',

invalid_amount : "Конфігурація дозволяє вказати мінальну" +
"      суму, для виконання якої необхідна загальна сума замовлення",
    
    details:"Опис",
    is_visible_in_store:"Видимий у закладі",
    is_item_in_stock:"Позиції на складі",
    email_or_phone:"Електронна пошта або номер телефону",
    for_use: 'Для користування',
    item:"Позиція",
    price:"Вартість",
    is_default_selected:"Обране по дефолту",
    is_user_selected:"Обране користувачем",
    specifications:"Специфікації",
        item_note_here:"Пункт примітку тут",
        
        new_password:"Новий пароль",
        old_password:"Старий пароль",
        country:"Країна",
        city:"Місто",
        delivery_type:"Тип доставки Type",
        item_name:"Назва елементу",
        
        is_default:"Видимий",
        is_in_stock:"В наявності",
        is_most_popular:"Найпопулярніший",
        specification_name:"Назва модифікатора",
        specification_type:"Тип",
        specification_detail:"Деталі",
        action:"Дія",
        item_specification_name:"Назва специфікації",
        select_type:"Оберіть тип",
        add_specification:"Додайте специфікацію",
        default_select:"Оберіть за замовчуванням",
        user_selected:"Вибір користувача",
        type_single:"Один",
        type_multiple:"Кілька",
        
        error_atleast_one_specification:"Оберіть хоча б одну специфікацію",
        do_not_default_select_morethan_range : 'не за замовчуванням вибирайте більше діапазону',
        
        item_tax:"Податок на елементі",
        is_business_store:"Бізнес",
        is_business: 'Бізнес',
        is_visible: 'Видимий',
        is_busy: 'Зайнятий',
        store_open_time:"Заклад відкривається в",
        store_close_time:"Заклад зачиняється в",
        free_delivery_for_above_order_price:"Безкоштовна доставка після вартості більшою ніж",
        free_delivery_within_radius: 'Безкоштовна доставка в радіусі',
        is_store_pay_delivery_fees:"Заклад платить за доставку?",

        completed:"Виконаний",
        remaining:"Залишився",

        manual: "посібник(ручний)",
        social: "соціал",


    width: "Ширина",
    height: "Висота",

        
        id:"Id",
        user:"Користувач",
        provider:"Кур'єр",
        payment_by:"Оплата",
        total:"Загалом",
        status:"Статус",
        card:"Картка",
        cash:"Готівка",
        user_rating:"Рейтинг користувача",
        provider_rating:"Рейтинг кур'єра",
        
        product_name:"Назва категорії",
        date_time:"Дата і час",
        date:"дата",
        
        sort:"Сортування",
        search:"Пошук",
        date_filter:"Фільтр по даті",
        ascending:"По зростанню",
        descending:"По спаданню",
        filter_id:"Id",
        filter_name:"Назва",
        value: 'Значення',
        expiry_date: 'Строк дії',
        filter_user:"Користувач",
        filter_provider:"Кур'єр",
        filter_item:"Елемент",
        filter_product:"Категорія",

        please_contact_to_admin:"Будь ласка, зв'яжіться з адміністратором",

        order:"Замовлення",
        service_fees:"Комісія сервісу",
        order_fees:"Комісія з замовлення",
        store_profit:"Прибуток закладу",
        paid_service_fee:"Сплачено за послуги сервісу",
        recieved_order_payment:"Отримана оплата замовлення",
        earning:"Заробіток",
        currency:"Валюта",
        admin_earning:"Заробіток адміністратора",
        provider_earning:"Заробіток кур'єра",
        pay_to_provider:"Сплатити кур'єру",
        pay_store:"Спалили закдалом",
        
        completed_order:"Виконане замовлення",
        cancelled_order: "Скасоване зомовлення",
        order_amount:"Сума замовлення",
        pay_by_admin:"Сплатити адміністратором",


        ////////// daily earning ///////
        item_price:"Вартість елемента",
        total_order_price:"Вартість замовлення",
        deduct_from_wallet: "Вивід з гаманця",
        added_in_wallet: "Додано в гаманець",
        admin_profit:"Прибуток адміністратора",
        wallet:"Гаманець",
        total_earnings:"Загальний дохід",
        paid_in_wallet: "ОПЛАЧЕНО У ГАМАНЦІ",
        paid: "ОПЛАЧЕНО",
        remaining_to_pay: "ЗАЛИШИЛОСЬ ЗАПЛАТИТИ",
        received_order_amount:"Отримана вартість замовлення",
        pay_to_store:"Оплатити в заклад",

        payment_status:"Статус оплати",
        no_of_item:"Номер елемента",
        total_cart_price:"Загальна вартість кошика",
        store_have_service_payment:"Оплата послуг заклада",
        total_store_income:"Загальний дохід від магазину",
        total_order:"Загальне замовлення",
        accepted_order:"Прийняте замовлення",
        
        referral_credit:"Реферальний кредит",
        total_referred:"Загальна кількість посилань",

        all:"ВСІ",
        yes:"ТАК",
        no:"НІ",

        doesnot_have_an_account:"Немає облікового запису?",
        store_title1:"Вітаємо в",
        app_name:"Delivery Lime",
        store_title2:"Store Panel",
        signin_to_your_account:"Вхід в аккаунт",
        forgot_password:"Забули пароль",

        offer:"Пропозиція",
        unique_code:"Унікальний код",
        exp_date:"Строк дії",

        order_payment_paid_by_store:"Оплата здійснюється закладом?",
        vehicle:"Транспортний засіб",


        ////////

        created_at: "Створений в",
        store_accepted_at: "Заклад прийняв в",
        preparing_order_at: "Готування замовлення почалось в",
        order_ready_at: "Замовлення готове в",
        store_order_send_at: "Заклад відіслав замовлення в",
        provider_accepted_at: "Кур'єр прийняв в",
        start_for_pickup_at: "Почав підбір в",
        arrived_on_store_at: "Прибув до закладу в",
        picked_order_at: "Замовлення забране в",
        start_for_delivery_at: "Початок доставки в",
        delivered_at: "Доставлений в",
        completed_at: "Виконаний в",


        //////////////////////////
        base_price:"Базова вартість",
        distance_price:"Вартість за дистанцію",
        time_price:"Вартість часу",
        service_price:"Оплата сервісу послуг",
        tax_price:"Податок",
        surge_price:"Різке збільшення цін",
        total_delivery_price:"ВАРТІСТЬ ДОСТАВКИ",
        promo_bonus:"Промо бонус",

        cart_price:"Вартість кошику",

        order_payment:"Оплата замовлення",
        delivery_payment:"Оплата доставки",

        ///////////

        wallet_payment:"Оплата з гаманця",
        cash_payment:"Оплата готівкою",
        other_payment:"Інший тип оплати",
        user_payment:"Оплата користувачем",

        profit:"Прибуток",
        items:"елементів",
        qty:"Кількість",
        order_completed:"ЗАМОВЛЕННЯ ВИКОНАНО",

        already_account:"У вас уже є профіль?",
        price_rating: "Рейтинг вартості",
        open_full_time: "Відкрито цілодобово",
        open: "Відчинено",
        sunday: "НД",
        monday: "ПН",
        tuesday: "ВТ",
        wednesday: "СР",
        thursday: "ЧТ",
        friday: "ПТ",
        saturday: "СБ",
        required: "Обов'язково",
        add_item_note: "Додати примітку",

        mobile_no: "Номер телефону",
        total_service_cost: "Загальна вартість сервісу",
        specification_price: "Вартість специфікацій",
        total_item_cost: "Загальна вартість елементів",


        first_name: "Ім'я",
        last_name: "Прізвище",
        enter_first_name: "Введіть ім'я",
        enter_last_name: "Введіть прізвище",
        enter_email: "Введіть Email",
        enter_mobile_no: "Введіть номер телефону",


        order_cancellation_charge_for_above_order_price: "Санкції вище вартості",
        is_order_cancellation_charge_apply: "Санкції за відміну",
        order_cancellation_charge_type: "Тип санкцій",
        order_cancellation_charge_value: "Значення санкцій",
        max_item_quantity_add_by_user: "Максимальна кількість елементів, яку користувач може додати",
        schedule_order_create_after_minute: "Мінімальний період часу за який користувач може здійснити передзамовлення",
        is_provide_delivery_anywhere: "Забезпечити кур'єрську доставку",
        is_provide_pickup_delivery: "Забезпечити самовивіз",
        delivery_radius: "Радіус доставки",
        is_taking_schedule_order: "Чи може користувач створювати передзамовлення?",
        inform_schedule_order_before_min: "Сповістити заклад перед приготуванням замовлення",
        min_order_price: "Мінімальна вартість замовлення",
        percentage: "Відсоткова",
        absolute: "Абсолютна",

        item_image_size_error: "Розширення зображення некоректне",
        item_image_ratio_error: "Співвідношення зображення некоректне",
        item_image_extension_error: "Розширення зображення некоректне",

        cancel_reason1: "Не наявна на складі позиція замовлення",
        cancel_reason2: "Адреса доставки не доступна",

        promo_code_name: "Назва",
        promo_code_type: "Тип",
    promo_code_value: "Значення",
    order_or_service: "Замовлення/Сервіс",
    uses: "Використовує",
    user_used: "Користувач використав",
    state: "Стан",
    promo_is_expired: "Чи дійсний",
    promo_apply_on:"Промо застосовується",
    is_active: "Активний",
    is_approved: "Одобрений",
    is_promo_required_uses: "Чи вимагає промо використання",
    is_promo_expiry_date: "Строк дії стікає",
    is_promo_have_minimum_amount_limit: "Ліміт мінімальної суми",
    is_promo_have_max_discount_limit: "Ліміт максимальної знижки",
    promo_code_uses: "кількість промодоків для використання(користувачів)",
    code_expiry: "Строк дії",
    promo_code_apply_on_minimum_amount: "Мінімальна сума",
    promo_code_max_discount_amount: "Максимальна знижка",
    start_date: "Дата початку",
    end_date:"Дата закінчення",
    admin_loyalty: "Адміністративна лояльність",
    promo_created_loyalty: "Промо-лояльність створено",
    promo_for: "Промо для",
    admin_loyalty_type: "Тип лояльності адміністратора",
    store: "Заклад",

    image_note1:" Завантажте максимум 5 зображень в межах ширини x висоти (мін " ,
    image_note2:" і макс ",
    image_note3:"Співвідношення зображення повинно бути ",
    image_note4:" і тільи для завантаження ",
    image_note5:" файл",
    note_for_image:"Примітка зображення",

    is_promo_apply_on_completed_order: "Застосувати акцію після виконаного замовлення",
    promo_apply_after_completed_order: "Мінімальне виконане замовлення",
    promo_recursion_type: 'Тип повторень',
    is_promo_have_date: 'Дата',
    start_time: 'Час початку',
    end_time: 'Час завершення',
    months: 'Місяць',
    days: 'День',
    weeks: 'Тиждень',

    is_promo_have_item_count_limit: 'Мінмальний ліміт елементів',
    promo_code_apply_on_minimum_item_count: 'Мінімальний елемент',

    category_already_exist: 'Категорія вже існує',
    enter_category_name: 'Введіть назву категорії',
    both: 'Обидва',
    order_type: 'Тип замовлення',
    payment_mode: 'Тип оплати',
    delivery_man: 'Кур\'єр',
    pickup: 'Підбір',
    request_id: 'Номер запиту',
    order_id: 'Номер замовлення',
    rejected: 'Відхилений',
    cancelled: 'Скасований',
    delivery_address: 'Адреса доставки',
    assigned_date: 'Дата назначення',

    item_specification: 'Модифікатор елемента',
    specification: 'Модифікатор',
    specification_group: 'Група модифікаторів ',
    select_file: 'Оберіть файл',
    update_item_specification: 'Оновити модифікатори елементу',

}

export var button = {
    download_demo_file: 'Завантажити демо EXCEL файл',
        add_modifier_group: 'Додато групу модифікаторів',
        submit:"Надіслати",
        register:"Реєстрація",
        view_modifier_group: 'Переглянути модифікатори',
        view_product: 'Переглянути категорію',
        login:"Вхід",
        login_button:"ВХІД",
        close:"Закрити",
        update:"Оновити",
        add_item:"Додати елемент",
        add_specification:"Додати специфікацію",
        add_product:"Додати категорію(продукт)",
        add:"Додати",
        save:"Зберегти",
    unavailable: 'недоступно',
        edit:"Редагувати",
        delete:"Видалити",
        remove:"Видалити",
        change:"Змінити",
        select_file:"Обрати файл",
        add_store_time:"Додати час",
        update_item:"Оновити елемент",
        view_specification:"Переглянути специфікації",
        view_full_invoice:"Переглянути весь чек",
        
        accept:"Прийняти",
        resject:"Відхилити",
        prepare_for_order:"Підготовка до замовлення",
        order_ready:"Замовлення готове",
        assign_delivery_for_provider:"Назначити на кур'єра",
        reassign_delivery_for_provider:"Переназначити",
        cancle:"Скасувати",
        cancel_request: "Скасувати",
        reject:"Відхилити",
        view_order_detail:"Переглянути деталі замовлення",
        view_cart_detail:"Переглянути деталі кошика",
        track_delivery_man:"Відслідковувати кур'єра",
        pre:"Попередній",
        next:"Наступний",
        get_confirmation_code: "Отримати код підтвердження",
        apply:"Застосувати",
        export_excel:"Експорт",
        price_paid_by_store:"Ціна оплачується закладом",
        ok: 'Ок',
    action: "Дії",
        register_now:"ЗАРЕЄСТРУВАТИСЯ ТЕПЕР",
        forgot_password:"Забули пароль?",
        sign_up:"Зареєструватися",
        to: "До",
    edit_order: "Редагувати замовлення",

        add_to_cart: "Додати в кошик",
        cart:"КОШИК",
        create_order_without_item: 'Створити замовлення без елементів',
        checkout: "CHECKOUT",
        clear_all: "очистити все",
        place_order: "Розмістити замовлення",
        quick_delivery: "Швидка доставка",
        confirmation_code: "Код підтвердження",
        complete_order: "Виконати",
        inActive: "Не активний",
        active: "Активний",
        add_promo: "Додати промокод",
        done: "Виконано",
    show_all: 'Показати все',
    activate: 'Активувати',
    cancel: 'Відмінити',
    detail: 'Деталі',
    invoice: 'Рахунок',
    import_data: 'Імпортувати дані'
    
}
export var status = {
    created:"Створений",
    waiting_for_accept1:"Замовлення створене",
    accepted1:"Прийнятий",
    start_preparing_order1:"Почати готування",
    order_ready1:"Готове",
    waiting_for_delivery_man1:"Назначений",
    delivery_man_accepted1:"Прийнятий",
    delivery_man_coming1:"В дорозі",
    delivery_man_arrived1:"Прибув",
    picked_order1:"Здійснити підбір",
    started_for_delivery1:"Доставляється",
    arrived_at_destination1:"Доставляється",
    delivered_ordered1:"Виконано",
    assign_order_to_Delivery_man1:"Назначити кур'єра",
    no_delivery_man_found1:"Не знайдено",
    delivery_man_rejected1:"Відхилено",
    delivery_man_cancelled1:"Відхилено",
    user_cancelled1:"Скасовано користувачем",
    oredr_complete:"Замовлення виконане",
    order_delivered:"Доставлено",
    completed:"Виконано",
    rejected1:"Відхилено",
    cancelled1:"Скасовано",
    not_completed:"Не виконано",
    user_cancelled:"Користувач відмінив",
    cancelled_request1: 'Не назначено',

    waiting_for_accept:"Нове замовлення створене",
    accepted:"Прийнято",
    start_preparing_order:"Почате приготування",
    order_ready:"Замовлення готове",
    waiting_for_delivery_man:"Назначено на кур'єра",
    delivery_man_accepted:"Кур'єр прийняв",
    delivery_man_coming:"Кур'єр в дорозі",
    delivery_man_arrived:"Кур'єр прибув",
    picked_order:"Кур'єр здійснив підбір замовлення",
    started_for_delivery:"Доставляється",
    arrived_at_destination:"Кур'єр прибув на місцепризначення",
    delivered_ordered:"Замовлення доставлено",
    assign_order_to_Delivery_man:"Назначити доставку на кур'єра",
    rejected:"Заклад відхилив",
    cancelled:"Заклад скасував замовлення",
    no_delivery_man_found:"Кур'єра не знайдено",
    delivery_man_rejected:"Кур'єр відхилив",
    delivery_man_cancelled:"Кур'єр скасував",
    cancelled_request: 'Запит спасований'

}


export var message = {
    specification_already_added:"Специфікація вже додана",
    item_already_exist:"Елемент вже в цій категорії",
    product_already_exist:"Назва категорії вже існує"
}

export var heading_title = {
    estimated_time_for_ready_order: "Приблизний час готового замовлення (хв)",
    complete_order: "Повне замовлення",
    product_title:"Дані категорії",
    specification_list:"Список специфікацій",
    item_title:"Дані про елемент",
    modifier_group: 'Група модифікаторів ',
    item_setting:"Налаштування елементу",
    item_specification:"Специфікації елементу",
    add_item_specification:"Додати елемент специфікації",
    store_setting_title:"Налаштування закладу",
    add_store_time:"Додати елемент до закладу",
    history:"Історія",
    order_list:"Список замовлень",
    delivery_list:"Список доставок",
    item_images:"Зображення елементу",
    total_earning:"Загальний заробіток",
    order_earning:"Заробіток замовлення",
    store_transactions: "Операції закладу",
    other_earning:"Інший заробіток",
    orders:"Замовлення",
    order_user_detail: 'Деталі замовлення',
    order_from: 'Замовлення від',
    delivery_to:'Доставити до',
    payment: 'Платіж',
    delivery_man: 'Кур\'єр',

    you_are_decline:"Ваш профіль був деактивований адміністратором",
    rating:"Рейтинг",

    total_order:"Загальне замовлення",
    accepted_order:"Прийняте замовлення",
    rejected_order:"Відхилене замовлення",
    completed_order:"Виконане замовлення",
    total_item_sold:"Загалом проданих елементів",
    accepted_ratio:"Співвідношення прийнятих",
    rejected_ratio:"Співвідношення відхилених",
    completed_ratio:"Співвідношенях виконнаних",
    daily_earning:"Денний прибуток",


    invoice_no:"Номер рахунку",
    user_detail:"Деталі користувача",
    provider_detail:"Деталі кур'єра",
    order_detail:"Деталі замовлення",
    order_status:"Статус замовлення",
    distance:"Дистанція",
    total_time:"Загальний час",
    total_items:"Загально елементів",
    delivery_fees:"КОМІСІЯ ДОСТАВКИ",
    total:"ЗАГАЛЬНО",
    quantity:"КІЛЬКІСТЬ",
    price:"ВАРТІСТЬ",
    cart:"КОШИК",
    order_fees:"КОМІСІЯ ЗАМОВЛЕННЯ",
    earning:"Заробіток",
    promo_setting: "Налаштування промо",
    promo_data: "Промо дані",
    product: "Категорія",
    category: 'Категорія',
    item: 'Елемент',
    add_modifier_group: 'Додати групу модифікаторів',
    ready_to_delivery: 'Готове для відправки',
    in_progress: 'В процесі',
    accepted: 'Прийняті',
    new_orders: 'Нові замовлення',

    order_price_settings: 'Налаштування вартості замовлення',
    order_cancellation_settings: 'Налаштування відміни замовлення',
    schedule_order_settings: 'Налаштування замовленя по розкладу',
    delivery_settings: 'Налаштування доставки',
    store_time:"Налаштування графіку роботи",
    select_tag:'Оберіть ТЕГИ на чому Ви спеціалізуєтесь',
    general_settings: 'Генеральні налаштування',
    upload_documents: 'Завантажити документи',
    add_provider: 'Реклама кур\'єра',
    p_accepted_order:"ПРИЙНЯТИЙ",
    p_completed_order:"ВИКОНАНИЙ",
    p_rejected_order:"ВІДХИЛЕНО",
    cancelled_order: "Скасоване замовлення"

}
export var lable_title = {
    cash:"Готівка",
    card:"Картка",
    absolute:"Абсолютне",
    percentage:"Відсоткове",
    order:"Замовлення",
    service:"Сервіс",
    active:"Активний",
    inactive:"Не активний",
    expired:"Минів термін дії",
    not_expired:"Не закінчився",
    store:"Недійсний",
    admin:"Адміністратор",
    sub_admin:"Суб адмін",
    provider:"Курє'р",
    user:"Користувач",
    provider_vehicle_type:"Транспортний засіб кур'єра",
    mandatory:"Обов'язковий",
    optional:"Додатковий(опція)",
    completed:"ВИКОНАНО",
    not_completed:"НЕ ВИКОНАНО",
    delivery_fees_paid_by_store:"ВАРТІСТЬ ДОСТАВКИ СПЛАЧУЄ ЗАКЛАД",
    asap:"ЯКНАЙШВИДШЕ",



    created_at:"Створений в",
    store_accepted_at:"Заклад прийняв в",
    preparing_order_at:"Готування замовлення в",
    order_ready_at:"Замовлення готове в",
    store_order_send_at:"Заклад відправив замовлення в",
    provider_accepted_at:"Кур'єр прийняв в",

    start_for_pickup_at:"Почав здійснювати підбір в",
    arrived_on_store_at:"Прибув до закладу в",
    picked_order_at:"Здійснив підбір замовлення в",
    start_for_delivery_at:"Почав здійснювати доставку в",
    delivered_at:"Доставлено в",
    completed_at:"Виконано в",


}