let http_url = 'http://localhost:8000'

export var GET_METHOD = {

    GET_COUNTRY_LIST : 'api/admin/get_country_list'
}



export var POST_METHOD = {
    REGISTER : '/api/franchise/register',
    STORE_REGISTER : '/api/store/register',
    ADMIN_OTP_VERIFICATION : '/api/admin/otp_verification',
    FORGOT_PASSWORD : '/api/admin/forgot_password',
    GET_CITY_LIST: '/api/admin/get_city_list',
    GET_DELIVERY_LIST_FOR_CITY: '/api/admin/get_delivery_list_for_city',
    GET_SETTING_DETAIL : '/api/admin/get_setting_detail',
    LOGIN : '/api/franchise/login',
    GET_FRANCHISE_DATA : '/api/franchise/get_franchise_data',
    GET_PRODUCT_LIST : '/api/franchise/get_product_list',
    GET_STORE_LIST : '/api/franchise/store_list_search_sort_franchises',
    LOGOUT: '/api/franchise/logout',
    UPDATE : '/api/franchise/update',
    GET_STORE_DATA : '/api/franchise/get_store_data',
    GET_IMAGE_SETTING : '/api/admin/get_image_setting',
    ADD_PRODUCT : '/api/franchise/add_product',
    GET_PRODUCT_DATA : '/api/franchise/get_product_data',
    GET_PRODUCT_STORE_LIST : '/api/franchise/get_product_store_data',
    UPDATE_PRODUCT : '/api/franchise/update_product',
    GET_SPECIFICATION_GROUP: '/api/franchise/get_specification_group',
    ADD_SPECIFICATION_GROUP : '/api/franchise/add_specification_group',
    DELETE_SPECIFICATION_GROUP : '/api/franchise/delete_specification_group',
    ADD_SPECIFICATION : '/api/franchise/add_specification',
    DELETE_SPECIFICATION : '/api/franchise/delete_specification',
    GET_STORE_PRODUCT_ITEM_LIST : '/api/franchise/get_store_product_item_list',
    GET_FOR_STORE_PRODUCT_ITEM_LIST : '/api/franchise/get_for_store_product_item_list',
    IS_ITEM_IN_STOCK: '/api/franchise/is_item_in_stock',
    GET_SOECIFICATION_LIST : '/api/franchise/get_specification_lists',
    GET_SPECIFICATION_LISTS : '/api/franchise/get_specification_lists',
    ADD_ITEM : '/api/franchise/add_item',
    GET_ITEM_DATA : '/api/franchise/get_item_data',
    UPDATE_ITEM : '/api/franchise/update_item',
    UPDATE_ITEM_IMAGE : '/api/franchise/update_item_image',
    DELETE_ITEM_IMAGE : '/api/franchise/delete_item_image',
    ORDER_LIST_SEARCH_SORT : '/api/franchise/order_list_search_sort',
    STORE_RATING_TO_USER:"/api/franchise/rating_to_user",
    STORE_RATING_TO_PROVIDER:"/api/franchise/rating_to_provider",
    DELIVERY_LIST_SEARCH_SORT : '/api/franchise/delivery_list_search_sort',
    GET_ORDER_DETAIL : '/api/franchise/get_order_detail',
    HISTORY : '/api/franchise/history',
    PROVIDER_LOCATION_TRACK : '/api/franchise/provider_location_track',
   /* CHECK_DETAIL : '/api/admin/check_detail',
    CANCEL_REQUEST : '/api/franchise/cancel_request',
    ORDER_PAYMENT_STATUS_SET_ON_CASH_ON_DELIVERY : '/api/franchise/order_payment_status_set_on_cash_on_delivery',
    SET_ORDER_STATUS : '/api/franchise/set_order_status',
    STORE_CANCEL_OR_REJECT_ORDER : '/api/franchise/store_cancel_or_reject_order',
    CREATE_REQUEST : '/api/franchise/create_request',
    STORE_COMPLETE_ORDER :"api/franchise/complete_order",
    ADD_ITEM_IN_CART: "api/user/add_item_in_cart",
    NEW_PASSWORD : '/api/admin/new_password',
    CHECK_REFERRAL: '/api/admin/check_referral',
    GET_DOCUMENT_LIST : '/api/admin/get_document_list',
    UPLOAD_DOCUMENT : '/api/admin/upload_document',
    GET_ORDER_CART_INVOICE: "api/user/get_order_cart_invoice",
    GET_USER :"/api/store/get_user",
    PAY_ORDER_PAYMENT: "api/user/pay_order_payment",
    CREATE_ORDER: "api/user/create_order",
    APPLY_PROMO_CODE: "api/user/apply_promo_code",
    GET_COUNTRY_PHONE_NUMBER_LENGTH: 'api/store/get_country_phone_number_length',

    UPLOAD_ITEM_IMAGE : '/api/store/upload_item_image',
    DAILY_EARNING : '/api/store/daily_earning',
    GET_STORE_EARNING : '/api/store/get_store_earning',
    CHANGE_DELIVERY_ADDRESS: 'api/user/change_delivery_address',
    GET_ORDER_DATA : '/api/store/get_order_data',
    ADD_PRODUCT : '/api/store/add_product',
    GET_STORE_DATA : '/api/store/get_store_data',
    OTP_VERIFICATION : '/api/store/otp_verification',
    UPDATE_STORE_TIME : '/api/store/update_store_time',
    REGISTER : '/api/store/register',
    WEEKLY_EARNING : '/api/store/weekly_earning',

    */

}