export var menu_title = {
    
}

export var sub_menu_title = {

    user: "Používateľ",
    block_user: "Zablokovaný Používateľ",
    online_providers:"Online",
    approved_providers:"Schválený",
    declined_providers:"Neschválený",
    stores:"Podniky",
    declined_stores:"Neschválený",
    business_off_stores:"Business Off",

}

export var setting_tab_title = {
    admin:"Admin",
    logo: "Logo",
    image_setting: "Nastavenie Obrazu",
    google_key_settings: "Nastavenia Google Key ",
    app_update_settings: "Nastavenia Aktualizácie Aplikácií",
    ios_push_notification: "Tlačiť Oznámenie (iOS)"
}

export var tooltip_title = {
    minimum_phone_number_length: "Zadajte minimálnu dĺžku telefónneho čísla",
    maximum_phone_number_length: "Zadajte maximálnu dĺžku telefónneho čísla",
    referral_bonus_to_user: "Zadajte sumu kreditu referenčného bonusu. Použivateľ by mal získať, ak by sa jeho referenčný kód použil. Mena kreditu bude predvolená mena krajiny.",
    referral_bonus_to_user_friend: "Zadajte sumu kreditu za referrenčny bonusu, ktorý by mal získať kamarat používateľa. Mena kreditu bude predvolená mena krajiny.",
    no_of_user_use_referral: "Toto číslo označuje maximálne použitie referrenčneho kódu používateľa. Ak je zadaný 2, používatelia ho použijú iba dvakrát.",
    referral_bonus_to_store: "Zadajte sumu kreditu referrenčneho bonusu. Podnik by mal získať, ak by sa jeho jeho referrenčny kód použil. Mena kreditu bude predvolená mena krajiny..",
    referral_bonus_to_store_friend: "Zadajte sumu kreditu referrenčneho bonusu, ktorý by mal kamarat podniku získať. Mena kreditu bude predvolená mena krajiny.",
    no_of_store_use_referral: "Toto číslo označuje maximálne použitie referenčného kódu podniku. Ak zadáte 2, rôzni kamaratí ho použijú iba dvakrát.",
    referral_bonus_to_provider: "Zadajte sumu kreditu referrenčneho bonusu, kuriér by mal získať, ak by sa jeho referrenčny kód použil. Mena kreditu bude predvolená mena krajiny.",
    referral_bonus_to_provider_friend: "Zadajte sumu kreditu referrenčneho bonusu, ktorý by mal kamarat kuriéra získať. Mena kreditu bude predvolená mena krajiny.",
    no_of_provider_use_referral: "Toto číslo označuje maximálne použitie referrenčného kódu kuriéra. Ak je zadaný 2, tak kód kuriéra sa požije iba dvakrát rôznymi kamarátmi.",
    base_price_distance: "Vyberte hodnotu voľnej vzdialenosti zahrnutej v základnej cene. Napr. ak su vybrané 2, tak cena za vzdialenosť sa nebude účtovať do 2 km alebo míle.",
    surge_multiplier: "Multiplikátor Nárastu",
    base_price: "Základná cena pre tento typ služby. Napr. $5 je základná cena pre SUV.",
    price_per_unit_distance: "Cena za km alebo míle pre tento typ služby.",
    price_per_unit_time: "Cena za jednotku času pre tento typ služby.",
    service_tax: "Percento dane z celkovej faktúry.",
    min_fare: "Minimálne cestovné.",
    cancellation_fee: "To sú poplatky účtované pri zrušení objednávky.",
    set_price_for_zone_to_zone: "Nastaviť fixnú dodaciu cenu za zónu do zóny."

}
export var filter = {


}

export var date_time_title = {

    
}

export var title = {

    //////////  date_time_title
    first_name: 'Meno',
    last_name: 'Priezvisko',
    assigned_date: 'Pridelený Dátum',
    expiry_date: "Dátum Splatnosti",
    start_date: "Dátum Začiatku",
    end_date: "Konečný Dátum",
    complete_date: "Dátum Dokončenia",
    create_date: "Vytvorený Dátum",
    start_time: 'Čas Začiatku',
    end_time: 'Čas Ukončenia',
    date: "Dátum",
    day: 'Ďeň',
    week: "Týždeň",
    month: "Mesiac",
    time: "Čas",
    year: "Rok",
    sunday: "Ne",
    monday: "Po",
    tuesday: "Ut",
    wednesday: "St",
    thursday: "Št",
    friday: "Pi",
    saturday: "So",

    ////// for filter
    SET_BY_ADMIN: 'Nastavene Správcom',
    ADDED_BY_CARD: 'Pridané Kartou',
    ADDED_BY_REFERRAL: 'Pridané Referralom',
    ORDER_CHARGED: 'Účtovaná Objednávka',
    ORDER_REFUND: 'Vrátenie Objednávky',
    SET_ORDER_PROFIT: 'Zisk na Objednávku',
    ORDER_CANCELLATION_CHARGE: 'Poplatok za Zrušenie Objednávky',
    SET_BY_WALLET_REQUEST: 'Nastavené na Základe Žiadosti o Peňaženku',
    sort: "Druh",
    search: "Vyhľadávanie",
    date_filter: "Filter Dátumu",
    ascending: "Ascendentný",
    descending: "Descendentný",
    comment: "Komentár",
    profit_mode: 'Režim zisku',
    dashboard: "Prístrojová Doska",
    delivery_info: "Dodacie Informácie",
    map_view: "Zobrazenie mapy",
    templates: "Šablóny",
    months: 'mesiac',
    weeks: 'týždeň',
    days: 'ďeň',
    order: "Objednávka",
    from_price: "від ціни",
    to_price: "до ціни",
    profit_fee: "прибуток",
    profit_value: "Hodnota Zisku",
    orders: "Objednávky",
    delivery: "Dodávka",
    deliveries: "Dodávky",
    history: "Historiá",
    payment: "Platba",
    payments: "Platby",
    approved: "Schválený",
    unapproved: "Neschválený",
    online: "Online",
    offline: "Offline",
    close: "Zavrieť",
    business_off: "Business Off",
    provider_track: "Cesta Kuriéra",
    deliveries_prices: "Cena za Dodávky",
    request_cancellation_reason: "Zrušené Dodávky",
    earning: "Zárobok",
    order_earning: "Zarábať objednávky",
    provider_weekly_earning: "Týždenný Zárobok Kuriéra",
    store_weekly_earning: "Ukladať Týždenné Zárobky",
    promo_code: "Promo Kód",
    referral_detail: "Referralny Detail",
    wallet_history: "História Peňaženky",
    wallet_request: "Žiadosť o Peňaženku",
    transaction_history: "História Transakcií",
    ads: "Reklamy",
    send_mass_notification: "Poslať hromadné oznámenie",
    admin: "Admin",
    sub_admin: "Sub Admin",
    user: "Používateľ",
    users: "Používatelia",
    provider: "Kutiér",
    providers: "Kuriéri",
    store: "Podnik",
    stores: "Podniky",
    settings: "Nastavenia",
    admin_settings: "Nastavenia Admina",
    app_settings: "Nastavenia Aplikácie",
    location: "Poloha",
    vehicle: "Vozidlo",
    store_location: 'Poloha Podnika',
    provider_location: 'Poloha Kuriéra',
    country: "Krajina",
    city: "Mesto",
    full_name: 'Celé meno',
    review: "Preskúmanie",
    document: "Document",
    documents: "Dokumenty",
    mail: "Pošta",
    sms: "SMS",
    detail: "Detail",
    details: "Detaily",
    no_of_record: 'Žiadny Záznam',
    referred_to: 'Uvedený',
    payment_mode: "Platobný Režim",
    item_price: "Cena Položky",
    tax_price: "Daňová Cena",
    earn: "Zarábať",
    card: 'Karta',
    cash: 'Hotovosť',
    wallet: "Peňaženka",
    other: "Ostatné",
    promo: "Promo",
    promo_payment: 'Promo Platba',
    card_payment: 'Platba Kartou',
    cash_payment: 'Platba v Hotovosti',
    wallet_payment: "Platba Peňaženkou",
    other_payment: "Iná Platba",
    order_payment: "Platba Objednávky",
    delivery_payment: "Dodavkova Platba",
    user_payment: "Platba Používateľa",
    store_profit: "Zisk z Obchodu",
    admin_profit: "Zisk Admina",
    admin_order_profit: "Zisk Objednávky Admina",
    admin_delivery_profit: "Dodavkova Platba Admina",
    deliveryman_profit: "Deliveryman Zisk",
    deliveryman_income: "Deliveryman Zárobok",
    store_income: "Zárobok z Obchodu",
    profit: "Zisk",
    profilt_mode: 'Režim Zisku',
    convert_rate: "Prevodný Kurz",
    all: "Všetko",
    business: "Podnik",
    visible: "Viditeľný",
    invisible: "Neviditeľný",
    active: "Aktívny",
    inactive: "Neaktívny",
    yes: 'Áno',
    no: 'Nie',
    like: "Like",
    dislike: "Dislike",
    url: "Url",
    name: "Meno",
    image: "Obraz",
    icon: "Icona",
    map_pin: "Map Pin",
    color: "Farba",
    code: "Kód",
    currency: "Mena",
    timezone: "Časové pásmo",
    km: "Km",
    mile: "Mi",
    miles: "Míle",
    id: "ID",
    unique_id: "Unikátne Id",
    email: "Email",
    phone: "Telefón",
    rate: "Rýchlosť",
    action: "Čin",
    qty: "Množstvo",
    spec: "Špec.",

    // for provider
    total: "Celkom",
    accepted: "Prijatý",
    cancelled: "Zrušený",
    completed: "Dokončený",
    rejected: "Odmietnuté",
    password: "Heslo",
    new_password: "Nové Heslo",
    confirm_password: "Potvrďte Heslo",
    old_password: "Staré Heslo",
    forgot_password: "Zabudol si Heslo",
    admin_title1: "Vitajte v",
    app_name: "Delivery Lime",
    admin_title2: "Admin Panel",
    signin_to_your_account: "Prihlásiť sa do svojho účtu",
    referred_by: "Predložené",
    total_referrals: "Celkový Počet Odporúčaní ",
    referral: "Odporučenie",
    referred: "Uvedené",
    referral_user: "Odporúčaný Používateľ",
    document_uploaded: "Dokument Nahraný",
    phone_number_verified: "Telefón Overený",
    email_verified: "Email Overený",
    app_version: "Verzia Aplikácie",
    device_type: "Typ Zariadenia",
    active_for_job: "Aktívne pre prácu",
    website_url: "Webobá Adresa Url",
    slogan: "Slogan",
    famous_for: "Známy",
    device_type_android: "Android",
    device_type_ios: "Ios",
    both: "Oba",
    message: "Správa",
    price_rating: "Hodnotenie Ceny",
    is_use_wallet: "Použiť Peňaženku",
    specification: "Špecifikácia",
    specifications: "Špecifikácie",
    product: "Produkt",
    products: "Produkty",
    item: "Položka",
    items: "Položky",

    //history
    status: "Stav",
    order_type: 'Typ objednávky',
    asap: 'ASAP',
    schedule: 'Plán',
    payment_by: "Platba",
    default_price: "Predvolená Cena",

    // earning
    fees: "Poplatky",
    address: "Adresa",
    price: "Cena",
    distance: "Vzdialenosť",

    /////// title with detail
    is_auto_transfer_for_store: 'Automatický Prenos Do Podnika',
    auto_transfer_day_for_store: 'Deň Automatického Prevodu Do Podnika ',
    is_auto_transfer_for_deliveryman: 'Autumatický Prenos Pre Kuriéra',
    auto_transfer_day_for_deliveryman: 'Deň Automatického Prevodu Pre Kuriéra',
    to_store: 'Do Podnika',
    to_deliveryman: 'Do Kuriéra',
    to_user: 'Používateľovi',
    not_available: 'Nie je k dispozícií',
    cancellation_charge: 'Stornovací Poplatok',
    is_store_can_add_provider: 'Podnik Môže Pridať Poskytovateľa',
    is_store_can_set_delivery_prices: 'Podnik Môže Nastaviť Dodacie Ceny',
    is_store_can_complete_order: 'Podnik Môže Dokončiť Objednávku',
    online_with_order: "Online S Objednávkou",
    offline_with_order: "Offline S Objednávkou",
    delivery_man_online_with_order: "Kuriér Online S Objednávkou",
    delivery_man_offline_with_order: "Kuriér Offline S Objednávkou",
    provider_vehicle_plate_no: "Doska No.",
    provider_vehicle_name: "Názov Vozidla",
    provider_vehicle_year: "Vehicle Roku",
    provider_vehicle_model: "Model",
    provider_vehicle_color: "Farba",
    
    provider_vehicle_service_type: "Typ Služby",
    registered_date: 'Registrovaný Dátum',
    provider_vehicle: 'Vozidlo Poskytovateľa',
    from_distance: 'Vzdialenosť od',
    to_distance: 'Vzdialenosť do',
    driver_fee: 'Poplatok Vodičovi',

    ///////////////for country //////////////////////////
    country_timezone: "Časové Pásmo Krajiny",
    currency_code: "Kód Meny",
    currency_sign: "Znak Meny",
    country_phone_code: "Telefónny Kód Krajiny",
    phone_number_length: "Dĺžka Telefónneho Čísla",
    minimum_phone_number_length: "Minimálna Dĺžka Telefónneho Č.",
    maximum_phone_number_length: "Maximálna Dĺžka Telefónneho Č.",
    referral_bonus_to_user: "Odporučany Bonus Pre Používateľa",
    bonus_to_user_referral: "Odporučany Bonus Pre Kamarára Používateľa",
    referral_bonus_to_store: "Odporučany Bonus Pre Podnik",
    bonus_to_store_referral: "Odporučany Bonus Pre Kamaráta Podnika",
    referral_bonus_to_provider: "Odporučany Bonus Pre Kuriéra",
    bonus_to_provider_referral: "Odporučany Bonus Pre Kamarata Kuriéra",
    is_distance_unit_mile: "Vzdialenosť Jednotky Míle",
    referral_for_user: "Odporúčanie Pre Používateľa",
    referral_for_store: "Odporúčanie Pre Podnik",
    referral_for_provider: "Odporúčanie Pre Kuriéra",

    ///////////////for city //////////////////////////
    promo_apply: "Použiť Promo",
    city_radius: "Rádius Mesta",
    city_lat: "Šírka",
    city_lng: "Dĺžka",
    select: 'Vybrať',
    languages: "Jazyky",
    description: "Opís",
    is_use_distance_calculation: 'Použiť Výpočet Vzdialenosti',
    add_delivery_price_setting: 'Všetka Dodacia Cena',
    is_check_provider_wallet_amount_for_received_cash_request: "Skontrolovať Sumu Peňaženky za Hotovosť",
    provider_min_wallet_amount_for_received_cash_request: "Min. Výška Peňaženky Kuriéra za Hotovosť",
    provider_earning_add_in_wallet_using_cash: "Suma Kuriéra Pridaná Do Peňaženky Hotovasťou",
    provider_earning_add_in_wallet_using_other: "Suma Kuriéra Pridaná Do Peňaženky Inou Platbou",
    store_earning_add_in_wallet_using_cash: "Suma Podnika Pridaná Do Peňaženky Hotovasťou",
    store_earning_add_in_wallet_using_other: "Suma Podnika Pridaná Do Peňaženky Inou Platbou",
    // NEW 
    zone: 'Zóna',
    use_radius: 'Použiť Rádius',
    ////////////////// for delivery /////////////////////
    famous_products_tags: "Značky Produktov",
    sequence_number: "Poradové Číslo",
    ////////// for service //////////////////////////
    base_price_distance: "Vzdialenosť Základnej Ceny",
    base_price: "Základná Cena",
    price_per_unit_distance: "Cena Za Jednotku Vzdialenosti",
    price_per_unit_time: "Cena Za Jednotku Času",
    service_tax: "Daň Zo Služieb",
    surge_price: "Nárast Ceny",
    min_fare: "Min Cestujúci",
    cancellation_fee: "Zrušenie Poplatkov",
    surge_hours: "Nárast Hodín",
    is_surge_hours: "Nárast Hodín",
    surge_multiplier: "Multiplikátor Nárastu",
    surge_start_hour: "Hodina Začiatku Nárastu",
    surge_end_hour: "Konečná Hodina Nárastu",
    last_updated: "Naposledy Aktualizovaný",
    created: "Vytvorený",
    total_item_sold: "Celková Predaná Položka",
    delivery_time: "Čas Kuriéra",
    store_item_tax: "Daň Z Tovaru",
    set_time: "Nastaviť Časový Rozvrh",
    store_time: "Čas Podniku",
    free_delivery_for_above_order_price: "Doprava Zadarmo Za Cenu Uvedenú Vyššie",
    is_store_pay_delivery_fees: "Podnik Platí Dodacie Poplatky",

    // For Promo code
    is_promo_required_uses: "Vyžaduje Sa Promo Používateľa",
    is_promo_have_minimum_amount_limit: "Min.Výška Limitu ",
    is_promo_have_max_discount_limit: "Max. Zľava Limitu",
    promo_code_apply_on_minimum_amount: "Min. Výška",
    promo_code_max_discount_amount: "Max. Výška Zľavý",
    admin_loyalty: "Lojálnosť",
    promo_created_loyalty: "Promo Vytvorený Lojalno",
    promo_for: "Promo Pre",
    admin_loyalty_type: "Typ Lojality",
    created_by: "Vytvoril",
    value: "Hodnota",
    type: "Typ",
    promo_code_uses: "Počet Použití",
    is_expired: "Vypršanie?",
    promo_for_delivery_service: "Promo Pre Doručovaciu Službu",
    uses: "Použitie",
    user_used: "Používateľ Použil",
    promo_apply_on: "Promo Aplikovať Na",

    //FOR NEW PROMO STRING
    is_promo_apply_on_completed_order: "Prihlásiť Sa Po Dokončení",
    promo_apply_after_completed_order: "Minimálna Dokončená Objednávka",
    promo_recursion_type: 'Typ Rekurzie',
    min_item_limit: 'Minimálny Limit Položky',

    promo_store:"Podnik",
    promo_for_delivery:"Dodávky",
    promo_delivery_service:"Donášková Služba",
    promo_product: "Produkt",
    promo_item: "Položka",
    contact_email: "Kontaktný Email",
    contact_phone: "Kontaktný Telefón",
    admin_panel_timezone: "Admin Panel Časové Pásmo",
    admin_logo: "Logo",
    admin_title_icon: "Názov Ikony",
    admin_mail_title_icon: "Obrázok Na Pozadí Pošty",
    admin_store_logo: "Logo Podniku",
    admin_mail_logo: "Logo Pošty",
    admin_user_logo: "Logo Použivateľa",

    //for app settings
    admin_provider_timeout: "Časový Limit Kuriéra",
    admin_store_timeout: "Časový Limit Podnika",
    admin_app_name: "Názov Aplikácie",
    admin_default_search_radius: "Predvolený Polomer Vyhľadávania",
    admin_scheduled_request_pre_start_minute: "Naplánované Požiadavky Pred Začatím Minút",
    admin_number_of_try_for_scheduled_request: "Počet Cyklov Pre Požiadavku Plánovača",

    // for google key settings
    android_user_app_gcm_key: "Android Používateľ Aplikácia Gcm Key",
    android_provider_app_gcm_key: "Android Kuruér Aplikácia Gcm Key",
    android_store_app_gcm_key: "Android Podnik Aplikácia Gcm Key",
    android_user_app_google_key: "Android Používateľ Aplikácia Google Key",
    android_provider_app_google_key: "Android Kuriér Aplikácia Google Key",
    android_store_app_google_key: "Android Podnik Aplikácia Google Key",
    ios_user_app_google_key: "IOS Používateľ Aplikácia Google Key",
    ios_provider_app_google_key: "IOS Kuriér Aplikácia Google Key",
    ios_store_app_google_key: "IOS Podnik Aplikácia Google Key",
    admin_panel_google_key: "Admin Panel Google Key",
    store_panel_google_key: "Podnikový Panel Google Key",
    branch_io_key: "Časť Io Kľúč",

    // other switch
    login_by_social: "Sociálne Prihlásenie",
    use_referral: "Použiť Odporúčanie",
    verify_email: "Potvrdiť Email",
    verify_phone: "Potvrdiť Telefón",
    upload_documents: "Nahráť Dokumenty",
    login_by_email: "Prihlásiť Sa E-mailom",
    login_by_phone: "Prihlásiť Sa Telefónom",
    profile_picture_required: "Profilový Obrázok",
    show_optional_field: "Zobraziť Pole Možností",
    earning_add_in_wallet_using_cash: "Čiastku Pridať Do Peňaženky Pomocou Platby V Hotovosti",
    earning_add_in_wallet_using_other: "Čiastku Pridať Do Peňaženky Inou Platbou",
    email_id_required: "Vyžaduje Sa Email",
    phone_required: "Vyžaduje Sa Telefón",
    sms_notification: "SMS Oznámenie",
    mail_notification: "Email Oznámenie",
    push_notification: "Tlačiť Oznámenie",
    pickup_delivery_confirmation_code: "Zdvihnúť Kód Potvrdenia O Doručení",
    complete_delivery_confirmation_code: "Dokončený Kód Potvrdenia O Doručení",

    // for app Update setting
    open_update_dialog: "Otvoriť Aktualizovaný Dialóg",
    force_update: "Vynútiť Aktualizáciu",
    certificate_mode: "Režim Certifikácie",
    push_certificate: "Tlačiť Certifikát",
    push_p8_file: 'Tlačiť Súbor P8',
    push_key_file:"Tlačiť Kľúčový Súbor",
    bundle_id:"Zväzok Id",
    team_id: 'Tím Id',
    key_id: 'Kľúč Id',
    passprase: "Passprase",
    sandbox_mode: "Pieskovisko",
    production_mode: "Produkcia",

    // for document
    is_mandatory: "Povinné",
    is_unique_code: "Jedinečný Kód",
    option: "Možnosť",
    unique_code: "Kód",
    item_note_here: "Poznámka Položky",

    //for sms
    sms_unique_title: "Jedinečný Názov SMS",
    select_sms_unique_title: "Vyberte Jedinečný Názov SMS",
    is_send: "Odoslaná",
    //for email
    email_unique_title: "Jedinečný Názov E-mailu",
    email_title: "Názov E-mailu",
    email_admin_info: "Informácie o Email Admin",
    email_content: "Obsah E-mailu",
    //for add wallet
    amount: "Čiastka",
    transfer_status: "Stav Prenosu",
    transfered_by: "Prenesené",
    transfered_by_admin: "Admin",
    transfer: "Prenos",
    not_transfer: "Neprenesený",
    // for admin sms
    content: "Písať Obsah SMS",
    notification_content: "Písať Obsah Oznámenia",
    // For Provider Weekly Earning
    admin_earn:"Admin Zarobiť",
    admin_earn_in_wallet: 'Admin Zarobiť Peňaženku',
    total_orders:"Celkový Počet Objednávok",
    provider_earn: "Kuriér Zarobiť",
    pay_to_provider :"Platiť/Zbierať",
    have_case: "Mať Hotovosť",
    pay_collect: 'Platiť/Zbierať',
    paid: "Platil",
    remaining_to_pay: "Zostáva Na Zaplatenie",
    view_week_statement: "Zobraziť Výpis Týždňa",
    pay: "Platiť",
    cancelled_by: "Zrušené",
    cancellation_reason: "Dôvod Zrušenia",
    store_earn: "Podnik Zarobiť",
    pay_to_store :"Platiť/Zbierať",
    store_have_payment: "Prijatá Platba",
    provider_earning:"Zárobok Kuriéra",
    deliveries_payment:"Platba za Dodávku",
    delivery_at:"Dátum Doručenia",
    store_bear_delivery_fee: 'Poplatok za doručenie obchodníka?',
    deliveryman_paid_order_cash_to_store: 'Kuriér zaplatil objednávku v hotovosti na uloženie?',
    sattlement_with_store: 'Vyrovnánie s podnikom',
    sattlement_with_deliveryman: 'Vyrovnánie s kurierom',
    payment_status: "Stav Platby",
    wallet_amount: "Množstvo Peňaženky",
    from_where: "Odkiaľ?",
    add_cut: "Pridať/Odrezať",
    order_start_at:"Dátum Začiatku",

    // earning
    invoice_number: "ČÍSLO FAKTÚRY",
    invoice_date: "DÁTUM",
    distance_price: "Cena Vzdialenosti",
    delivery_fee: "Dodacie Poplatky",
    time_price: "Časová Cena",
    service_price: "Cena Služby",
    pickup: 'Zdvihnúť',
    cart: "VOZÍK",
    order_fee: "POPLATKY ZA OBJEDNÁVKU",
    cart_price: "Cena Košíka",
    store_tax_price: "Daňová Cena",
    order_price: "Cena Objednávky",
    total_online_time: "Online Čas",
    job_time: "Čas Práce",
    not_answered: "Neodpoveda",
    sms_configuration_auth_id: "Autorizácie ID",
    sms_auth_token: "Autorizácie Tokenu",
    sms_number: "Číslo",
    sms_gateway_name: "SMS Brána",
    total_transferred_amount: 'Prevedený',
    paid_service_fee: "Platený Servisný Poplatok",
    no_of_item: "Žiadná Položka",
    total_cart_price: "Celková Cena Košíka",
    total_store_income: "Celkový Príjem z Podniku",
    received_order_amount: "Prijatá Suma Objednávky",
    paid_order_amount: "Suma Zaplatenej Objednávky",
    deduct_from_wallet: "Odpočítať z Peňaženky",
    added_in_wallet: "Pridané do Peňaženky",
    total_earnings: "Celkový Zárobok",
    paid_in_wallet: "ZAPLATENÉ V PEŇAŽENKE",
    beneficiary_address: "Adresa Príjemcu",
    bank_swift_code: "Bankový Swift Kód",
    branch: "Časť",
    account_number: "Číslo Účtu",
    ads_type: "Typ Reklamy",
    website: "Webová Stránka",
    delivery_list: "Zoznam Dodávok",
    store_list: "Zoznam Podnikov",
    in_store: "V Podniku",
    redirect_to_store: "Presmerovať Na Podnik?",
    ratio_should_be: "Pomer By Mal Byť",
    min_width: "Min Šírka",
    max_width: "Max Šírka",
    min_height: "Min Výška",
    max_height: "Max Výška",
    min: "Minimum",
    max: "Maximum",
    open_full_time: "Otvorené na Plný Úväzok",
    open: "Otvorené",
    image_size_error: "Veĺkosť Obrázka Nie Je Správna",
    image_ratio_error: "Pomer Obrázka Nie Je Spravný",
    image_extension_error: "Rozšírenie Obrázka Nie Je Správne",
    reviewed_by: 'Hodnotené',
    icon_image_note: "Nahrajte veľkosť obrázka do šírky x výšky ( ",
    image_note1: "Nahrajte veľkosť obrázka do šírky x výšky (min ",
    image_note2: " a max ",
    image_note3: "Pomer obrázkov by mal byť ",
    image_note4: " a nahtáte iba ",
    image_note5: " súbor",
    note_for_image: "Poznámka k Obrázku",
    note_for_map_pin: "Poznámka pre Map Pin",
    note_for_icon: "Poznámka pre Ikonu",
    provider_paid_order: "Kuriér Zaplatil Objednávku",
    earning_store_have_payment:"Podnik Má Platbu ",
    cash_card: "Hotovosť/Karta",
    provider_have_cash: "Kuriér Má Hotovosť",
    provider_fees: "Poplatky Kuriera",
    pay_provider: "Zaplatiť Kuriérovi",
    store_fees: "Poplatky Podniká",
    store_paid_delivery_fees: "Podnik Zaplatil Dodacie Poplatky",
    pay_store: "Zaplatiť Podnikovi",
    cancellation_fees: "Zrušenie Poplatkov",
    refund_amount: "Čiastka Náhrady",
    provider_income_set_in_wallet: "Kuriér Položil Peňaženku",
    order_id: "Objednať ID",
    user_id: "Používateľ ID",
    request_id: "Žiadosť ID",
    provider_id: "Kuriér ID",
    store_id: "Podnik ID",
    total_wallet_income_set_in_cash_order: "Odpočet Peňaženky",
    total_wallet_income_set_in_other_order: "Pridané Do Peňaženky",
    store_income_set_in_wallet: "Podnik Položil Peňaženku",
    total_item: "Celkom Položiek",
    delivery_price: "Dodacia Cena",
    promo_bonus: "Promo Bonus",
    store_have_service_payment: "Podnik Má Servisné Platby",
    store_have_order_payment: "Podnik Má Platbu Za Objednávku",
    provider_have_cash_payment: 'Poskytovateľ má hotovostnú platbu',
    admin_profit_on_store: "Zisk Na Objednávku Admina",
    admin_profit_on_delivery: "Zisk Doručenia Admina",
    total_referred: "Celkom Odporúčané",
    referral_code: "Referenčný Kód",
    offer: "Ponuka",
    remining_to_pay: "ZOSTÁVA NA ZAPLATENIE",
    read_more: "Čítať",
    user_review_to_provider: "Používateľ Na Kuréra",
    user_review_to_store: "Použivateľ Na Podnik",
    provider_review_to_user: "Kuriér Na Použivateľa",
    provider_review_to_store: "Kuriér Na Podnik",
    store_review_to_provider: "Podnik Na Kuriéra",
    store_review_to_user: "Podnik Na Použivateľa",
    bank_account_holder_name: "Majiteľ Bankového Účtu",
    ads_for: "Reklamy Na",
    image_for_banner: "Obrázor Bannera",
    image_for_fullscreen: "Celoobrazovkový",
    block: "BLOK",
    general: "Všeobecný",
    for_delivery: "Na Donášku",
    banner: "Baner",
    fullscreen: "Celoobrazovkový",
    delivery_type: "Druh Dodávky",

    delivery_image_size_error: "Veľkosť Obrázka Nie Je Správna",
    delivery_image_ratio_error: "Obrazový Pomer Nie Je Správny",
    delivery_image_extension_error: "Rozšírenie Obrázka Nie Je Správne",
    vehicle_image_size_error: "Veľkosť Obrázka Nie Je Správna",
    vehicle_image_ratio_error: "Obrazový Pomer Nie Je Správny",
    vehicle_image_extension_error: "Rozšírenie Obrázka Nie Je Správne",
    ads_image_size_error: "Veľkosť Obrázka Nie Je Správna",
    ads_image_ratio_error: "Obrazový Pomer Nie Je Správny",
    ads_image_extension_error: "Rozšírenie Obrázka Nie Je Správne",
    remaining: "Ostatný",
    delivery_address: 'ADRESA DODANIA',

    /////////////// labels
    absolute: "Absolútny",
    percentage: "Percento",
    not_completed: "NEDOKONČENE",
    delivery_fees_paid_by_store: "DODACIE POPLATKY ZAPLATENÉ PODNIKOM",
    not_expired: "Nevypršala Platnosť",
    created_at: "Vytvorené O",
    store_accepted_at: "Podnik Prijatý O",
    preparing_order_at: "Príprava Objednávky O",
    order_ready_at: "Objednávka Pripravená O",
    store_order_send_at: "Objednávka Podniku Odoslana O",
    provider_accepted_at: "Kuriér Prijal O",
    start_for_pickup_at: "Začať Vyzdvihnutie O",
    arrived_on_store_at: "Dorazil Do Podniku O",
    picked_order_at: "Objedávka Vybratá O",
    start_for_delivery_at: "Začatie Dodávky O",
    delivered_at: "Dodané O",
    completed_at: "Dokončené O",

}

export var heading_title = {
    daily_earning: 'Denný Zárobok',
    add_vehicle: 'Pridať Vozidlo',
    delivery_price_setting: 'Nastavenie Dodacej Ceny',
    order_by: 'OBJEDNÁVKA OD',
    order_to: 'OBJEDNÁVKA PRE',
    deliver_by: 'VÝDANÝ',
    admin_menu: "Zoznam menu",
    order_user_detail: 'Podrobnosti o Objednávke Používateľa',
    create_mass_notification: "Vytvoriť Hromadné Oznámenie",
    order_fees: "POPLATKY ZA OBJEDNÁVKU",
    earning: "Zárobok",
    delivery_fees: "DODACIE POPLATKY",
    dashboard_register_detail: "Detail Registrácie",
    dashboard_order_detail: "Detaily Objednávky",
    dashboard_payment_detail: "Platobné Údaje",
    review_detail: "Detail Recenzie",
    dashboard_admin_payment: "Platby Admina",
    dashboard_store_payment: "Platby Podniku",
    dashboard_provider_payment: "Platby Kuriéra",
    dashboard_title: "Zárobok",
    dashboard_order_chart: "Graf Objednávok",
    dashboard_last_six_month_payment_detail: "Detaily o Platbe za Posledných 6 Mesiacov",
    rejection_reason: 'DÔVOD ZAMIETNUTIA',
    cancellation_reason: 'DÔVOD ZRUŠENIA',
    referral_setting: 'Odporúčané Nastavenia',
    country_data: "Údaje o Krajinách",
    setting: "Nastavenie",
    city_setting: "Nastavenie Mesta",
    country_setting: "Nastavenie Krajiny",
    delivery_setting: "Nastavenie Mesta",
    vehicle_setting: "Nastavenie Mesta",
    service_setting: "Nastavenie Služby",
    city_data: "Údaje o Meste",
    service_data: "Službove Údaje",
    surge_hour_data: "Údaje o Rázovej Hodine",
    vehicle_data: "Údaje o Vozidle",
    delivery_data: "Dodacie Údaje",
    payment_data: "Platobné Údaje",
    document_data: "Údaje Dokumentu",
    total_order: "Celková Objednávka",
    accepted_order: "Prijať Objednávku",
    rejected_order: "Zamietnutá Objednávka",
    completed_order: "Dokončená Objednávka",
    total_item_sold: "Celková Predaná Položka",
    accepted_ratio: "Akceptovaný Pomer",
    rejected_ratio: "Odmietnutý Pomer",
    completed_ratio: "Dokončený Pomer",
    assigned_date: 'Pridelený Dátum',
    order_for: 'OBJEDNÁVKA NA',
    not_answered: 'Neodpovedany',
    store_time: "Úložiť Čas",
    // app update
    android_user_app: "Aplikácia Používateľa Androidu",
    android_provider_app: "Kuriérska Aplikácia pre Android",
    android_store_app: "Podniková Aplikácia pre Android",
    ios_user_app: "Aplikácia Používateľa IOS",
    ios_provider_app: "Kuriérska Aplikácia pre IOS",
    ios_store_app: "Podniková Aplikácia pre IOS",
    user_app: "Aplikácia Používateľa",
    provider_app: "Kuriérska Aplikácia",
    store_app: "Podniková Aplikácia",
    other_setting: "Iné Nastavenia",
    promo_data: "Promo Údaje",
    promo_setting: "Promo Nastavenia",
    admin_data: "Údaje Admina",
    sms_data: "SMS ÚDAJE",
    email_data: "EMAIL ÚDAJE",
    add_wallet_amount: "Pridať Množstvo Peňaženky",
    admin_sms: "Poslať SMS",
    admin_send_notification: "Poslať Oznámenie",
    email_configuration: "Konfigurácia E-mailu",
    sms_configuration: "Konfigurácia SMS",
    history: "História",
    deliveries: "Dodávky",
    order_list: "Zoznam Objednávok",
    order_detail: "DETAILY OBJEDNÁVOK",
    user_detail: "DETAIL POUŽÍVATEĹA",
    delivery_user_detail: "DETAIL POUŽÍVATEĹA DODÁVKY",
    provider_detail: "DETAIL KURIÉRA",
    store_detail: "DETAIL PODNIKU",
    order_status: "STAV OBJEDNÁVKY",
    request_status: "STAV ŽIADOSTI",
    vehicle: "Vozidlo",
    wallet: "Peňaženka",
    referral: "Odporučenie",
    private_message: "Súkromná Správa",
    service_detail: "Detail Služby",
    promo_info: "Promo Informácie",
    user_info: "Informácie O Používateľovi",
    order_earning: "ZARÁBAŤ NA OBJEDNÁVKACH",
    daily_order_earning: "DENNÉ ZARÁBANIE NA OBJEDNÁVKACH",
    provider_transaction: "KURIÉRSKA TRANSAKCIA",
    store_transaction: "PODNIKOVÁ TRANSAKCIA",
    payment_gateway_data: "ÚDAJE PLATOBNEJ BRÁNY",
    bank_detail: "Banka",
    ads_data: "Údaje o Reklamách",
    advertise_data: "Inzerovať Údaje",
    image_size_for_delivery: "Veľkosť Obrázka Použitá Pre Dadávku/Produkt/Položku",
    image_size_for_map: "Veľkosť Obrázka PreImage Mapy Pin Pre Aplikácie",
    image_icon_size: "Veľkosť Ikony Obrázka",
    order_from: 'Objednať Od',
    delivery_to: 'Doručiť Do',
    payment: 'Platba',
    delivery_man: 'Kuriér',
    store: "Podnik",
    card: "Karta",
    cash: "Hotovosť",
    store_transactions : "Transakcie"

}

export var button = {
    
    add: "Pridať",
    edit: "Upraviť",
    delete: "Vymazať",
    save: "Uložiť",
    submit: "Predložiť",
    update: "Aktualizovať",
    login: "Prihlásiť Sa",
    register: "Registrovať",
    close: "Zavrieť",
    decline: "Neprijať",
    approved: "Schvaľovať",
    send: "Poslať",
    apply: "Použiť",
    export_excel: "Export",
    accept: "Súhlasiť",
    cancel: "Zrušiť",
    transfer: "Transfer",
    complete: "Dokončený",
    done: "Hotové",
    reassign : "Reassign",
    add_city: "Pridať Mesto",
    add_country: "Pridať Krajinu",
    add_delivery: "Pridať Dodávku",
    add_vehicle: "Pridať Vozidlo",
    add_service: "Pridať Službu",
    add_payment: "Pridať Platbu",
    add_wallet: "Pridať Peňaženku",
    add_document: "Pridať Dokument",
    add_promo: "Pridať Promo",
    add_admin: "Pridať Admina",
    add_ads: "Pridať Reklamy",
    
    inActive: "NeAktívny",
    active: "Aktívny",
    
    view_products: 'Zobraziť Kategóriu',
    view_setting: 'Zobraziť Nastavenia',
    view_map: "Zobraziť Mapu",
    view_invoice: "Zobraziť Faktúru",
    view_uses: "Zobraziť Použitie",
    view_cart: "Zobraziť Cart Detail ",
    
    usage: 'použitie',
    select_file: "Vyberte Súbor",
    remove_file: "Odstráňte Súbor",
    upload_file: "Nahrajte Súbor",
    detail: "Detail",
    send_sms: "Poslať SMS",
    send_notification: "Poslať Oznámenie",
    pre: "Pre",
    next: "Ďalšie",
    goto: "Ísť do",
    reviews: 'Preskúmanie',
    referral: 'Postúpenie',
    bank_detail: 'Bank Detail',
    view_document: "Dokumenty",
    vehicle_details : "Detaily Vozidla",
    select_vehicle: "Vyberte Vozidlo"
}

export var wallet_request_status = {
    created: "Vytvorený",
    sent: "Poslaný",
    accepted: "Prijatý",
    transfered: "Prenesený",
    completed: "Hotový",
    cancelled: "Zrušený"
}

export var status = {
    
    created: "Vytvorená",
    waiting_for_accept1: "Objednávka vytvorená",
    accepted1: "Prijatý",
    start_preparing_order1: "Prebieha",
    order_ready1: "Pripravený",
    waiting_for_delivery_man1: "Pridelený",
    delivery_man_accepted1: "Prijatý",
    delivery_man_coming1: "Príchod",
    delivery_man_arrived1: "Prišiel",
    picked_order1: "Zdvihol",
    started_for_delivery1: "Dodávanie",
    arrived_at_destination1: "Dodávanie",
    delivered_ordered1: "Hotový",
    assign_order_to_Delivery_man1: "Priradiť do Kuriéra",
    no_delivery_man_found1: "Nenájdené",
    delivery_man_rejected1: "Odmietnuté",
    delivery_man_cancelled1: "Odmietnuté",
    user_cancelled1: "Zrušené Použivateľom",
    oredr_complete: "Objednávka Dokončená",
    order_delivered: "Dodaný",
    completed: "Hotový",
    rejected1: "Odmietnuté",
    cancelled1: "Zrušený",
    not_completed: "Nedokončené",
    user_cancelled: "Používateľ zrušený",
    cancelled_request1: 'Nepridelený',
    waiting_for_accept: "Vytvorená Nová Objednávka",
    accepted: "Prijatý",
    start_preparing_order: "Začal Sa Pripravovať",
    order_ready: "Objednávka je pripravená",
    waiting_for_delivery_man: "Priradený Do Kuriéra",
    delivery_man_accepted: "Kuriér prijal",
    delivery_man_coming: "Kuriér prichádza",
    delivery_man_arrived: "Kuriér prišiel",
    picked_order: "Kuriér vyzdvihol objednavku",
    started_for_delivery: "Dodávanie",
    arrived_at_destination: "Kuriér pricestoval do cieľového mesta",
    delivered_ordered: "Objednávka Doručená",
    assign_order_to_Delivery_man: "Priradiť Do Kuriéra",
    rejected: "Podnik Zamietnutý",
    cancelled: "Uložiť Zrušenú Objednávku",
    no_delivery_man_found: "Kuriér nenašiel sa",
    delivery_man_rejected: "Kuriér Odmietnutý",
    delivery_man_cancelled: "Kuriér Zrušený",
    cancelled_request: 'Žiadosť Zrušena'
}


export var message = {
    country_already_exist: "Krajina Už Existuje",
    promo_code_already_exist: "Promo Kód Už Existuje"
}