export var menu_title = {
    
}

export var sub_menu_title = {

    user: "Користувач",
    block_user: "Заблокувати користувача",
    online_providers:"В онлайні",
    approved_providers:"Затверджені",
    declined_providers:"Незатверджені",
    stores:"Заклади",
    declined_stores:"Незатверджені",
    business_off_stores:"Незавершене виробництво",

}

export var setting_tab_title = {
    admin:"Адміністратор",
    logo: "Лого",
    image_setting: "Налаштування зображення",
    google_key_settings: "Налаштування Google Key",
    app_update_settings: "Налаштування оновлення додатків",
    ios_push_notification: "Сповіщення iOS"
}

export var tooltip_title = {
    minimum_phone_number_length: "Введіть мінімальну кількість цифер номеру телефону",
    maximum_phone_number_length: "Введіть максимальну кількість цифер номеру телефону",
    referral_bonus_to_user: "Введіть суму реферального бонусного кредиту, який користувач повинен отримати, якщо використовується його реферальний код. Валюта кредиту буде валютою країни по дефолту.",
    referral_bonus_to_user_friend: "Введіть суму реферального бонусного кредиту, який повинен отримати товариш користувача. Валюта кредиту буде валютою країни.",
    no_of_user_use_referral: "Це значення вказує на максимальну кількість використовування реферального коду користувача. Якщо ввести 2, тоді код користувача буде використовуватись тільки 2 рази різними товаришами.",
    referral_bonus_to_store: "Введіть суму реферального бонусного кредиту, який заклад повинен отримати, якщо використовується його реферальний код. Валюта кредиту буде валютою країни по дефолту.",
    referral_bonus_to_store_friend: "Введіть суму реферального бонусного кредиту, який повинен отримати товариш закладу. Валюта кредиту буде валютою країни.",
    no_of_store_use_referral: "Це значення вказує на максимальну кількість використовування реферального коду закладу. Якщо ввести 2, тоді код закладу буде використовуватись тільки 2 рази різними товаришами.",
    referral_bonus_to_provider: "Введіть суму реферального бонусного кредиту, який кур'єр повинен отримати, якщо використовується його реферальний код. Валюта кредиту буде валютою країни по дефолту.",
    referral_bonus_to_provider_friend: "Введіть суму реферального бонусного кредиту, який повинен отримати товариш кур'єра. Валюта кредиту буде валютою країни.",
    no_of_provider_use_referral: "Це значення вказує на максимальну кількість використовування реферального коду кур'єра. Якщо ввести 2, тоді код кур'єра буде використовуватись тільки 2 рази різними товаришами.",
    base_price_distance: "Оберіть значення для вільної відстані, що покривається базовою варістю. Наприклад, якщо обрано 2, тоді вартість відстані не буде підніматись до 2 км.",
    surge_multiplier: "Мультиплікатор перенапруги",
    base_price: "Базова вартість для даного виду послуг. Наприклад, 5 доларів - це базова ціна для позашляховика.",
    price_per_unit_distance: "Вартість за км для даного виду послуг.",
    price_per_unit_time: "Ціна за одиницю часу для даного виду послуг.",
    service_tax: "Процент податку на загальну суму рахунку-фактури.",
    min_fare: "Мінімальний тариф.",
    cancellation_fee: "Збір за анулювання замовлення.",
    set_price_for_zone_to_zone: "Встановити фіксовану вартість доставки від зони до зони."
}

export var filter = {


}

export var date_time_title = {

    
}

export var title = {

    //////////  date_time_title
    first_name: 'Ім\'я',
    last_name: 'Фамілія',
    assigned_date: 'Назначена дата',
    expiry_date: "Строк дії",
    start_date: "Дата початку",
    end_date: "Дата кінця",
    complete_date: "Дата завершення",
    create_date: "Дата створення",
    start_time: 'Час початку',
    end_time: 'Час закінчення',
    date: "Дата",
    day: 'День',
    week: "Тиждень",
    month: "Місяць",
    time: "Час",
    year: "Рік",
    sunday: "Нд",
    monday: "Пн",
    tuesday: "Вт",
    wednesday: "Ср",
    thursday: "Чт",
    friday: "Пт",
    saturday: "Сб",

    ////// for filter
    SET_BY_ADMIN: 'Встановити адміністратором',
    ADDED_BY_CARD: 'Додано карткою',
    ADDED_BY_REFERRAL: 'Додано реферальним',
    ORDER_CHARGED: 'Замовлення доручено',
    ORDER_REFUND: 'Повернення замовлення',
    SET_ORDER_PROFIT: 'Прибуток від замовлення',
    ORDER_CANCELLATION_CHARGE: 'Відміна замовлення',
    SET_BY_WALLET_REQUEST: 'Встановлюється за запитом гаманця',
    sort: "Сортувати",
    search: "Шукати",
    date_filter: "Фільтр дати",
    ascending: "Повернення",
    descending: "Вхідний",
    comment: "Коментар",
    profit_mode: 'Режим прибутку',
    dashboard: "Інформаційна дошка",
    delivery_info: "Інформація про доставку",
    map_view: "Перегляд карти",
    templates: "Шаблони",
    months: 'місяць',
    weeks: 'тиждень',
    days: 'день',
    order: "Замовлення",
    profit_value: "Значення прибутку",
    orders: "Замовлення",
    delivery: "Доставка",
    deliveries: "Доставки",
    history: "Історія",
    payment: "Платіж",
    payments: "Платежі",
    approved: "Затверджені",
    unapproved: "Незатверджені",
    online: "Онлайн",
    offline: "Офлайн",
    close: "Зачинено",
    business_off: "Незавершене виробництво",
    provider_track: "Шлях доставки",
    deliveries_prices: "Вартості доставки",
    request_cancellation_reason: "Відміна доставки",
    earning: "Заробіток",
    order_earning: "Заробіток із замовлення",
    provider_weekly_earning: "Тижневий заробіток кур'єра",
    store_weekly_earning: "Тижневий заробіток закладу",
    promo_code: "Промокод",
    referral_detail: "Інформація про реферальний код",
    wallet_history: "Історія гаманця",
    wallet_request: "Запит гаманця",
    transaction_history: "Історія транзакцій",
    ads: "Реклама",
    send_mass_notification: "Відправити масові сповіщення",
    admin: "Адміністратор",
    sub_admin: "Субадміністратор",
    user: "Користувач",
    users: "Користувачі",
    provider: "Кур'єр",
    providers: "Кур'єри",
    store: "Заклад",
    stores: "Заклади",
    settings: "Налаштування",
    admin_settings: "Налаштування адміністратора",
    app_settings: "Налаштування додатків",
    location: "Місцеположення",
    vehicle: "Автомобіль",
    store_location: 'Місцеположення закладу',
    provider_location: 'Місцеположення кур\'єра',
    country: "Країна",
    city: "Місто",
    full_name: 'Повне ім\'я',
    review: "Огляд",
    document: "Документ",
    documents: "Документи",
    mail: "Пошта",
    sms: "SMS",
    detail: "Інформація",
    details: "Інформації",
    no_of_record: 'Номер запису',
    referred_to: 'По відношенню до',
    payment_mode: "Режим оплати",
    item_price: "Вартість елементу",
    tax_price: "Вартість послуги",
    earn: "Заробити",
    card: 'Карта',
    cash: 'Готівка',
    wallet: "Гаманець",
    other: "Інше",
    promo: "Промо",
    promo_payment: 'Промо-оплата',
    card_payment: 'Оплата карткою',
    cash_payment: 'Оплата готівкою',
    wallet_payment: "Оплата з гаманця",
    other_payment: "Інша оплата",
    order_payment: "Оплата замовлення",
    delivery_payment: "Оплата доставки",
    user_payment: "Платіж користувача",
    store_profit: "Прибуток закладу",
    admin_profit: "Прибуток адміністратора",
    admin_order_profit: "Прибуток адміністратора за замовлення",
    admin_delivery_profit: "Прибуток адміністратора за доставку",
    deliveryman_profit: "Прибуток кур'єра",
    deliveryman_income: "Дохід кур'єра",
    store_income: "Дохід закладу",
    profit: "Прибуток",
    profilt_mode: 'Режим прибутку',
    convert_rate: "Швидкість конвертації",
    all: "Всі",
    business: "Зайнятий",
    visible: "Видимий",
    invisible: "Невидимий",
    active: "Активний",
    inactive: "Неактивний",
    yes: 'ТАК',
    no: 'НІ',
    like: "Вподобання",
    dislike: "Невдоволення",
    url: "Url",
    name: "Ім'я",
    image: "Зображення",
    icon: "Іконка",
    map_pin: "Map Pin",
    color: "Колір",
    code: "Код",
    currency: "Валюта",
    timezone: "Часовий пояс",
    km: "Км",
    mile: "Миля",
    miles: "Миль",
    id: "ID",
    unique_id: "Унікальний Id",
    email: "Електронний адрес",
    phone: "Номер телефону",
    rate: "Рейтинг",
    action: "Дія",
    qty: "Кількість",
    spec: "Спец.",

    // for provider
    total: "Загалом",
    accepted: "Прийняті",
    cancelled: "Скасовані",
    completed: "Завершені",
    rejected: "Відхилені",
    password: "Пароль",
    new_password: "Новий пароль",
    confirm_password: "Підтвердити пароль",
    old_password: "Старий пароль",
    forgot_password: "Забули пароль?",
    admin_title1: "Ласкаво просимо до",
    app_name: "Delivery Lime",
    admin_title2: "Панель адміністратора",
    signin_to_your_account: "Увійти в свій аккаунт",
    referred_by: "Відноситься до",
    total_referrals: "Загальна кількість рефералів",
    referral: "Реферал",
    referred: "Відкладено",
    referral_user: "Реферальний користувач",
    document_uploaded: "Документ завантажений",
    phone_number_verified: "Номер телефону перевірено",
    email_verified: "Електронна пошта перевірена",
    app_version: "Версія додатку",
    device_type: "Тип девайсу",
    active_for_job: "Активний для роботи",
    website_url: "Url вебсайту",
    slogan: "Лозунг",
    private_key: "Private Key",
    public_key: "Public Key",
    famous_for: "Відомий для",
    device_type_android: "Android",
    device_type_ios: "Ios",
    both: "Обидва",
    message: "Повідомлення",
    price_rating: "Рейтинг вартості",
    is_use_wallet: "Гаманці, що використовуються",
    specification: "Специфікація",
    specifications: "Специфікації",
    product: "Продукт",
    products: "Продукти",
    item: "Елемент",
    items: "Елементи",

    //history
    status: "Статус",
    order_type: 'Тип замовлення',
    asap: 'ASAP',
    schedule: 'Графік',
    payment_by: "Оплата за",
    default_price: "Дефолтна вартість",

    // earning
    fees: "Збори",
    address: "Адреса",
    price: "Варість",
    distance: "Відстань",

    /////// title with detail
    is_auto_transfer_for_store: 'Автоматичний переказ для закладу',
    auto_transfer_day_for_store: 'День авотматичного переказу для закладу',
    is_auto_transfer_for_deliveryman: 'Автоматичний переказ для кур\'єра',
    auto_transfer_day_for_deliveryman: 'День авотматичного переказу для кур\'єра',
    to_store: 'Закладу',
    to_deliveryman: 'Кур\'єру',
    to_user: 'Користувачу',
    not_available: 'Нема в наявності',
    cancellation_charge: 'Відміна',
    is_store_can_add_provider: 'Заклад може додати кур\'єра',
    is_store_can_set_delivery_prices: 'Заклад може встановлювати варість доставки',
    is_store_can_complete_order: 'Заклад може завершувати замовлення',
    online_with_order: "Онлайн із замовленням",
    offline_with_order: "Офлайн із замовленням",
    delivery_man_online_with_order: "Кур'єр онлайн із замовленням",
    delivery_man_offline_with_order: "Кур'єр офлайн із замовленням",
    provider_vehicle_plate_no: "Номер борту",
    provider_vehicle_name: "Найиенування автомобіля",
    provider_vehicle_year: "Рік випуску автомобіля",
    provider_vehicle_model: "Модель",
    provider_vehicle_color: "Колір",
    
    provider_vehicle_service_type: "Тип послуги",
    registered_date: 'Дата реєстрації',
    provider_vehicle: 'Автомобіль кур\'єра',
    from_distance: 'Початкова відстань',
    to_distance: 'Кінцева відстань',
    driver_fee: 'Кур\'єрський збір',

    from_price: 'From Price',
    to_price: 'To Price',
    profit_fee: 'Profit Value',
    add_delivery_profit_setting: 'Add Profit Value',
    from_price_not_greater_than_to_price: 'From Price not greater than To Price',
    submit : 'Add',

    ///////////////for country //////////////////////////
    country_timezone: "Часовий пояс",
    currency_code: "Код валюти",
    currency_sign: "Знак валюти",
    country_phone_code: "Телефонний код країни",
    phone_number_length: "Довжина номеру телефона",
    minimum_phone_number_length: "Мінімальна довжина номеру телефона",
    maximum_phone_number_length: "Максимальна довжина номеру телефона",
    referral_bonus_to_user: "Реферальний бонус користувача",
    bonus_to_user_referral: "Реферальний бонус товариша користувача",
    referral_bonus_to_store: "Реферальний бонус закладу",
    bonus_to_store_referral: "Реферальний бонус товариша закладу",
    referral_bonus_to_provider: "Реферальний бонус кур'єра",
    bonus_to_provider_referral: "Реферальний бонус товариша кур'єра",
    is_distance_unit_mile: "Дистанція в милях",
    referral_for_user: "Реферальний для корстувача",
    referral_for_store: "Реферальний для закладу",
    referral_for_provider: "Реферальний для кур'єра",

    ///////////////for city //////////////////////////
    promo_apply: "Промо-додаток",
    city_radius: "Радіус міста",
    city_lat: "Широта",
    city_lng: "Довгота",
    select: 'Обрати',
    languages: "Мови",
    description: "Опис",
    is_use_distance_calculation: 'Використовувати розрахунок відстані',
    add_delivery_price_setting: 'Додати вартість доставки',
    is_check_provider_wallet_amount_for_received_cash_request: "Сума чекового гаманця за готівку",
    provider_min_wallet_amount_for_received_cash_request: "Сума мінімального гаманця кур'єра при сплаті готівкою",
    provider_earning_add_in_wallet_using_cash: "Сума кур'єра додається в гаманець при сплаті готівкою",
    provider_earning_add_in_wallet_using_other: "Сума доставки додається в гаманець при сплаті іншим платежем",
    store_earning_add_in_wallet_using_cash: "Сума закладу додається в гаманець при сплаті готівкою",
    store_earning_add_in_wallet_using_other: "Сума закладу додається в гаманець при при сплаті іншим платежем",
    // NEW 
    zone: 'Зона',
    use_radius: 'Радіус використання',
    ////////////////// for delivery /////////////////////
    famous_products_tags: "Теги продуктів",
    sequence_number: "Нумерація послідовності",
    ////////// for service //////////////////////////
    base_price_distance: "Базова вартість відстані",
    base_price: "Базова вартість",
    price_per_unit_distance: "Вартість за одиницю відстані",
    price_per_unit_time: "Вартість за одиницю часу",
    service_tax: "Податок сервісу",
    surge_price: "Різке збільшення цін",
    min_fare: "Мінімальний тариф",
    cancellation_fee: "Відміна зборів",
    surge_hours: "Час пік",
    is_surge_hours: "Час пік",
    surge_multiplier: "Мультиплеєр перенавантаженості",
    surge_start_hour: "Час запуску перенавантаженості",
    surge_end_hour: "Час закінчення перенавантаженості",
    last_updated: "Останнє оновлення",
    created: "Створений",
    total_item_sold: "Всього продано",
    delivery_time: "Час доставки",
    store_item_tax: "Податок на товари",
    set_time: "Встановити розклад",
    store_time: "Час зберігання",
    free_delivery_for_above_order_price: "Безкоштовна доставки за вищою вартістю",
    is_store_pay_delivery_fees: "Сплата доставки закладом",

    // For Promo code
    is_promo_required_uses: "Потребується промо-користування",
    is_promo_have_minimum_amount_limit: "Мінімальний розмір",
    is_promo_have_max_discount_limit: "Максимальний розмір знижки",
    promo_code_apply_on_minimum_amount: "Мінімальна сума",
    promo_code_max_discount_amount: "Максимальна сума знижки",
    admin_loyalty: "Лояльність",
    promo_created_loyalty: "Створена лояльність промо",
    promo_for: "Промо для",
    admin_loyalty_type: "Тип лояльності",
    created_by: "Створений",
    value: "Значення",
    type: "Тип",
    promo_code_uses: "Кількість користувань",
    is_expired: "Строк дії закінчується?",
    promo_for_delivery_service: "Промо для сервісу доставки",
    uses: "Користування",
    user_used: "Використаний користувачем",
    promo_apply_on: "Промо-додаток включений",

    //FOR NEW PROMO STRING
    is_promo_apply_on_completed_order: "Подати заявку по завершенню",
    promo_apply_after_completed_order: "Мінімальне завершене замовлення",
    promo_recursion_type: 'Тип повторення',
    min_item_limit: 'Мінімальна кулькість товарів',

    promo_store:"Заклад",
    promo_for_delivery:"Доставки",
    promo_delivery_service:"Сервіс доставки",
    promo_product: "Продукт",
    promo_item: "Товар",
    contact_email: "Контактна електронна адреса",
    contact_phone: "Контактний номер телефону",
    admin_panel_timezone: "Адміністративна панель",
    admin_logo: "Лого",
    admin_title_icon: "Титульна іконка",
    admin_mail_title_icon: "Пошта зображення заднього фону",
    admin_store_logo: "Лого закладу",
    admin_mail_logo: "Лого пошти",
    admin_user_logo: "Лого користувача",

    //for app settings
    admin_provider_timeout: "Deliveryman TimeOut",
    admin_store_timeout: "Store TimeOut",
    admin_app_name: "Назва додатку",
    admin_default_search_radius: "Радіус пошуку за замовчуванням",
    admin_scheduled_request_pre_start_minute: "Scheduled Request Pre Start Minutes",
    admin_number_of_try_for_scheduled_request: "Number Of Loop For Scheduled Request",

    // for google key settings
    android_user_app_gcm_key: "Android User App Gcm Key",
    android_provider_app_gcm_key: "Android Deliveryman App Gcm Key",
    android_store_app_gcm_key: "Android Store App Gcm Key",
    android_user_app_google_key: "Android User App Google Key",
    android_provider_app_google_key: "Android Deliveryman App Google Key",
    android_store_app_google_key: "Android Store App Google Key",
    ios_user_app_google_key: "IOS User App Google Key",
    ios_provider_app_google_key: "IOS Deliveryman App Google Key",
    ios_store_app_google_key: "IOS Store App Google Key",
    admin_panel_google_key: "Admin Panel Google Key",
    store_panel_google_key: "Store Panel Google Key",
    branch_io_key: "Branch Io Key",

    // other switch
    login_by_social: "Вхід за допомогою соціальних мереж",
    use_referral: "Use Referral",
    verify_email: "Перевірити Email",
    verify_phone: "Перевірити номер мобільного телефону",
    upload_documents: "Завантажити документи",
    login_by_email: "Вхід за допомогою Email",
    login_by_phone: "Вхід за допомогою мобільного телефону",
    profile_picture_required: "Зображення профілю",
    show_optional_field: "Показати необов'язкові поля",
    earning_add_in_wallet_using_cash: "Сума, додана в гаманець при оплаті готівкою",
    earning_add_in_wallet_using_other: "Сума, додана в гаманець іншим платежем",
    email_id_required: "Email обов'язковий",
    phone_required: "Номер телефону обов'язковий",
    sms_notification: "SMS сповіщення",
    mail_notification: "Email сповіщення",
    push_notification: "Push сповіщення",
    pickup_delivery_confirmation_code: "Pickup Delivery Confirmation Code",
    complete_delivery_confirmation_code: "Complete Delivery Confirmation Code",

    // for app Update setting
    open_update_dialog: "Open Update Dialog",
    force_update: "Force Update",
    certificate_mode: "Certificate Mode",
    push_certificate: "Push Certificate",
    push_p8_file: 'Push P8 File',
    push_key_file:"Push Key File",
    bundle_id:"Bundle Id",
    team_id: 'Team Id',
    key_id: 'Key Id',
    passprase: "Passprase",
    sandbox_mode: "Sandbox",
    production_mode: "Production",

    // for document
    is_mandatory: "Обов'язково",
    is_unique_code: "Унікальний код",
    option: "Варіант",
    unique_code: "Код",
    item_note_here: "Пункт примітки",

    //for sms
    sms_unique_title: "SMS унікальна назва",
    select_sms_unique_title: "Оберіть унікальну назву SMS",
    is_send: "Надіслати",
    //for email
    email_unique_title: "Email унікальна назва",
    email_title: "Email титул",
    email_admin_info: "Email інформація адміністратора",
    email_content: "Email контент",
    //for add wallet
    amount: "Кількість",
    transfer_status: "Статус передання",
    transfered_by: "Передано",
    transfered_by_admin: "Адміністратор",
    transfer: "Перевід",
    not_transfer: "Не перевід",
    // for admin sms
    content: "Написати SMS контент",
    notification_content: "Написати вміст сповіщення",
    // For Provider Weekly Earning
    admin_earn:"Заробіток адміністратора Earn",
    admin_earn_in_wallet: 'Гаманець адміністратора',
    total_orders:"Всього замовлень",
    provider_earn: "Заробіток кур'єра",
    pay_to_provider :"Сплатити/Зібрати",
    have_case: "Володіти готівкою",
    pay_collect: 'Сплатити/Зібрати',
    paid: "Сплачено",
    remaining_to_pay: "Залишок на оплату",
    view_week_statement: "Перегляд заяви за тиждень",
    pay: "Оплатити",
    cancelled_by: "Скасовано",
    cancellation_reason: "Причина відмови",
    store_earn: "Заробіток закладу",
    pay_to_store :"Сплатити/Зібрати",
    store_have_payment: "Платіж отриманий",
    provider_earning:"Заробіток кур'єра",
    deliveries_payment:"Виплати кур'єра",
    delivery_at:"Дата доставки",
    store_bear_delivery_fee: 'Store bear delivery fee?',
    deliveryman_paid_order_cash_to_store: 'Курє\'єр сплатить готівку в закладі?',
    sattlement_with_store: 'Розрахунок з закладом',
    sattlement_with_deliveryman: 'Розрахунок з кур\'єром',
    payment_status: "Статус платежа",
    wallet_amount: "Сума гаманця",
    from_where: "Звідки?",
    add_cut: "Додати/Вирізати",
    order_start_at:"Початкова дата",

    // earning
    invoice_number: "НОМЕР РАХУНКУ",
    invoice_date: "ДАТА",
    distance_price: "Вартість дистанції",
    delivery_fee: "Вартість доставки",
    time_price: "Вартість часу",
    service_price: "КОМІСІЯ СЕРВІСУ",
    pickup: 'Підбір',
    cart: "КОШИК",
    order_fee: "КОМІСІЇ ЗАМОВЛЕННЯ",
    cart_price: "Вартість кошику",
    store_tax_price: "Вартість податку",
    order_price: "Вартість замовлення",
    total_online_time: "Онлайн час",
    job_time: "Час роботи",
    not_answered: "Без відповіді",
    sms_configuration_auth_id: "Auth ID",
    sms_auth_token: "Auth Token",
    sms_number: "Номер",
    sms_gateway_name: "SMS шлюх",
    total_transferred_amount: 'Переведений',
    paid_service_fee: "Платний сервісний збір",
    no_of_item: "Відсутній товар",
    total_cart_price: "Загальна вартість корзини",
    total_store_income: "Загальний дохід закладу",
    received_order_amount: "Сума отриманого замовлення",
    paid_order_amount: "Сума сплаченого замовлення",
    deduct_from_wallet: "Вивід з рахунку",
    added_in_wallet: "Додано до гаманця",
    total_earnings: "Загальний заробіток",
    paid_in_wallet: "ОПЛАТА В ГАМАНЦІ",
    beneficiary_address: "Адреса бенефеціару",
    bank_swift_code: "Банківський SWIFT код",
    branch: "Філіал",
    account_number: "Номер рахунку",
    ads_type: "Тип реклами",
    website: "Вебсайт",
    delivery_list: "Список доставок",
    store_list: "Список закладів ",
    in_store: "В наявності",
    redirect_to_store: "Перенаправити в магазин?",
    ratio_should_be: "Відношення повинно бути",
    min_width: "Мінімальна ширина",
    max_width: "Максимальна ширина",
    min_height: "Мінімальна висота",
    max_height: "Максимальна висота",
    min: "Мінімум",
    max: "Максимум",
    open_full_time: "Відкритий повний робочий день",
    open: "Відкрито",
    image_size_error: "Розміри не підходящі",
    image_ratio_error: "Співвідношення не коректне",
    image_extension_error: "Розширення зображення не підходяще",
    reviewed_by: 'Переглянуто',
    icon_image_note: "Завантажити зображення розміром ширини x висоти ( ",
    image_note1: "Розширення зобрження повинне бути в межах ширини x висоти (мін ",
    image_note2: " і макс ",
    image_note3: "Співвідношення повинно бути ",
    image_note4: " та завантажити тільки ",
    image_note5: " файл",
    note_for_image: "Примітки до зображення",
    note_for_map_pin: "Примітка піна для мапи",
    note_for_icon: "Піктограма примітка",
    provider_paid_order: "Deliveryman Paid Order",
    earning_store_have_payment:"Store Have Payment",
    cash_card: "Готівка/Картка",
    provider_have_cash: "Кур'єр має готівку",
    provider_fees: "Вартість доставки",
    pay_provider: "Pay Deliveryman",
    store_fees: "Тарифи заклада",
    store_paid_delivery_fees: "Заклад сплачує доставку",
    pay_store: "Pay Store",
    cancellation_fees: "Плата за відміну",
    refund_amount: "Сумма повернення",
    provider_income_set_in_wallet: "Кур'єр встановив гаманець",
    order_id: "Замовлення ID",
    user_id: "Користувач ID",
    request_id: "Запит ID",
    provider_id: "Кур'єр ID",
    store_id: "Заклад ID",
    total_wallet_income_set_in_cash_order: "Зняття з гаманця",
    total_wallet_income_set_in_other_order: "Додано у гаманець",
    store_income_set_in_wallet: "Заклад встановив гаманець",
    total_item: "Всього елементів",
    delivery_price: "Вартість доставки",
    promo_bonus: "Промо бонус",
    store_have_service_payment: "Оплата послуг закладу",
    store_have_order_payment: "Заклад має можливість оплатити замовлення",
    provider_have_cash_payment: 'Кур\'єр має готівковий платіж',
    admin_profit_on_store: "Прибуток адміністатора закладу",
    admin_profit_on_delivery: "Прибуток Адміністратора доставки",
    total_referred: "Всього відкладено",
    referral_code: "Реферальний код",
    offer: "Пропозиція",
    remining_to_pay: "ЗАЛИШОК ДО СПЛАТИ",
    read_more: "Читати",
    user_review_to_provider: "Користувач для кур'єра",
    user_review_to_store: "Користувач для закладу",
    provider_review_to_user: "Кур'єра для користувача",
    provider_review_to_store: "Кур'єра для закладу",
    store_review_to_provider: "Заклад для кур'єра",
    store_review_to_user: "Заклад для користувача",
    bank_account_holder_name: "Власник банківського рахунку",
    ads_for: "Реклама для",
    image_for_banner: "Банерне зображення",
    image_for_fullscreen: "Повноекранне зображення",
    block: "БЛОК",
    general: "Загальний",
    for_delivery: "Для доставки",
    banner: "Банер",
    fullscreen: "На весь дисплей",
    delivery_type: "Тип доставки",

    delivery_image_size_error: "Розмір зображеня не відповідає",
    delivery_image_ratio_error: "Співвідношення зображення не відповідає",
    delivery_image_extension_error: "Розширення зображення не відповідає",
    vehicle_image_size_error: "Розмір зображеня не відповідає",
    vehicle_image_ratio_error: "Співвідношення зображення не відповідає",
    vehicle_image_extension_error: "Розширення зображення не відповідає",
    ads_image_size_error: "Розмір зображеня не відповідає",
    ads_image_ratio_error: "Співвідношення зображення не відповідає",
    ads_image_extension_error: "Розширення зображення не відповідає",
    remaining: "Залишок",
    delivery_address: 'АДРЕС ДОСТАВКИ',

    /////////////// labels
    absolute: "Абстолютне",
    percentage: "Відсоткове",
    not_completed: "НЕ ВИКОНАНЕ",
    delivery_fees_paid_by_store: "ВАРТІСТЬ ДОСТАВКИ СПЛАУЄТЬСЯ ЗАКЛАДОМ",
    not_expired: "Не стікший строк дії",
    created_at: "Створений в",
    store_accepted_at: "Заклад прийняв в",
    preparing_order_at: "Готування замовлення почалось в",
    order_ready_at: "Замовлення готове в",
    store_order_send_at: "Заклад відіслав замовлення в",
    provider_accepted_at: "Кур'єр прийняв в",
    start_for_pickup_at: "Почав підбір в",
    arrived_on_store_at: "Прибув до закладу в",
    picked_order_at: "Замовлення забране в",
    start_for_delivery_at: "Початок доставки в",
    delivered_at: "Доаставлений в",
    completed_at: "Виконаний в",

}

export var heading_title = {
    daily_earning: 'Денний заробіток',
    add_vehicle: 'Додати транспортний заклад',
    delivery_price_setting: 'Налаштування вартості доставки',
    order_by: 'ЗАМОВИТИ НА',
    order_to: 'ЗАМОВИТИ ДО',
    deliver_by: 'Доставити на',
    admin_menu: "Список меню",
    order_user_detail: 'Деталі замовлення користувача',
    create_mass_notification: "Створити масове сповіщення",
    order_fees: "ВАРТІСТЬ ЗАМОВЛЕНЬ",
    earning: "Заробіток",
    delivery_fees: "ВАРТІСТЬ ДОСТАВКИ",
    dashboard_register_detail: "Деталі реєстрації",
    dashboard_order_detail: "Деталі замовлення",
    dashboard_payment_detail: "Деталі оплати",
    review_detail: "Деталі обзору",
    dashboard_admin_payment: "Адміністративні платежі",
    dashboard_store_payment: "Платежі закладу",
    dashboard_provider_payment: "Кур'єрські платежі",
    dashboard_title: "Заробіток",
    dashboard_order_chart: "Гістограма замовлень",
    dashboard_last_six_month_payment_detail: "Останні 6 місяців платежів",
    rejection_reason: 'ПРИЧИНА ВІДМОВИ',
    cancellation_reason: 'ПРИЧИНА СКАСУВАННЯ',
    referral_setting: 'Реферал налаштування',
    country_data: "Дані про країну",
    setting: "Налаштування",
    city_setting: "Налаштування міста",
    country_setting: "Налаштування країни",
    delivery_setting: "Налаштування доставки",
    vehicle_setting: "Налаштування транспортного засобу",
    service_setting: "Налаштування сервісу",
    city_data: "Дані міста",
    service_data: "Дані сервісу",
    surge_hour_data: "Дані про час пік години",
    vehicle_data: "Дані транспортних засобів",
    delivery_data: "Дані доставки",
    payment_data: "Дані про оплату",
    document_data: "Дані документа",
    total_order: "Загальні замовлення",
    accepted_order: "Прийняте замовлення",
    rejected_order: "Відмовлені замовлення",
    completed_order: "Виконані замовлення",
    total_item_sold: "Всі продані елементи",
    accepted_ratio: "Прийнятий показний",
    rejected_ratio: "Відмінений показник",
    completed_ratio: "Виконаний показний",
    assigned_date: 'Назначена дата',
    order_for: 'ЗАМОВЛЕННЯ ДЛЯ',
    not_answered: 'Без відповіді',
    store_time: "Час закладу",
    // app update

    android_user_app: "Android User App",
    android_provider_app: "Android Deliveryman App",
    android_store_app: "Android Store App",
    ios_user_app: "IOS User App",
    ios_provider_app: "IOS Deliveryman App",
    ios_store_app: "IOS Store App",
    user_app: "Клієнтський додаток",
    provider_app: "Додаток для кур'єра",
    store_app: "Додаток для закладу",
    other_setting: "Інші налаштування",
    promo_data: "Промо дані",
    promo_setting: "Промо налаштування",
    admin_data: "Дані адміністратора",
    sms_data: "SMS ДАНІ",
    email_data: "EMAIL ДАНІ",
    add_wallet_amount: "Додати суму до гаманцю",
    admin_sms: "надіслати SMS",
    admin_send_notification: "Надіслати сповіщення",
    email_configuration: "Email конфігурація",
    sms_configuration: "SMS конфігурація",
    history: "Історія",
    deliveries: "Deliveries",
    order_list: "Список замовлень",
    order_detail: "ДЕТАЛІ ЗАМОВЛЕННЯ DETAILS",
    user_detail: "ДЕТАЛІ КОРИСТУВАЧА",
    delivery_user_detail: "ІНФОРМАЦІЯ ПРО ДОСТАВКУ",
    provider_detail: "ДЕТАЛІ КУР'ЄРА",
    store_detail: "ДЕТАЛІ ЗАКЛАДУ",
    order_status: "СТАТУС ЗАМОВЛЕННЯ",
    request_status: "СТАН ЗАПИТУ",
    vehicle: "Транспортний засіб",
    wallet: "Гаманець",
    referral: "Реферал",
    private_message: "Приватні повідомлення",
    service_detail: "Сервісна інформація",
    promo_info: "Промо інформація",
    user_info: "Інформація про користувача",
    order_earning: "ПРИБУТОК ПО ЗАМОВЛЕННЯХ",
    daily_order_earning: "ДЕННИЙ ПРИБУТОК",
    provider_transaction: "КУР'ЄРСЬКІ ТРАНЗАКЦІЇ",
    store_transaction: "ТРАНЗАКЦІЇ ЗАКЛАДУ ",
    payment_gateway_data: "ПЛАТІЖНИЙ ШЛЮЗ",
    bank_detail: "Банк",
    ads_data: "Дані про рекламу",
    advertise_data: "Рекламні данні",
    image_size_for_delivery: "Використання розміру зображення доставки/продукту/елементу",
    image_size_for_map: "Розмір картинки для мапи",
    image_icon_size: "Розмір піктограми зображення",
    order_from: 'Замовлення від',
    delivery_to: 'Доставка до',
    payment: 'Оплата',
    delivery_man: 'Кур\'єр',
    store: "Заклад",
    card: "Картка",
    cash: "Готівка",
    store_transactions : "Операції"

}

export var button = {
    
    add: "Додати",
    edit: "Редагувати",
    delete: "Видалити",
    save: "Зберегти",
    submit: "Відправити",
    update: "Оновити",
    login: "Вхід",
    register: "Реєстрація",
    close: "Закрити",
    decline: "Відмовитись",
    approved: "Затвердити",
    send: "Надіслати",
    apply: "Застосувати",
    export_excel: "Експорт",
    accept: "Прийняти",
    cancel: "Скасувати",
    transfer: "Перевести",
    complete: "Виконати",
    done: "Готово",
    
    add_city: "Додати місто",
    add_country: "Додати країну",
    add_delivery: "Додати доставку",
    add_vehicle: "Додати транспортний засіб",
    add_service: "Додати сервіс",
    add_payment: "Додати оплати",
    add_wallet: "Додати гаманець",
    add_document: "Додати документи",
    add_promo: "Додати промо",
    add_admin: "Додати адміністратора",
    add_ads: "Додати рекламу",
    
    inActive: "InActive",
    active: "Активний",
    
    view_products: 'Переглянути категорії',
    view_setting: 'Переглянути налаштування',
    view_map: "Переглянути мапу",
    view_invoice: "Переглянути рахунок",
    view_uses: "Переглянути використання",
    view_cart: "Переглянути деталі кошику",
    
    usage: 'використання',
    select_file: "Обрати файл",
    remove_file: "Видалити файл",
    upload_file: "Завантажити файл",
    detail: "Деталі",
    reassign: "Перепризначити",
    send_sms: "Надіслати SMS",
    send_notification: "Надіслати сповіщення",
    pre: "Пре",
    next: "Далі",
    goto: "Goto",
    reviews: 'Перегляд',
    referral: 'Реферал',
    bank_detail: 'Банківські реквізити',
    view_document: "Документи",
    vehicle_details : "Деталі транспортного засобу",
    select_vehicle: "Оберіть транспортний засіб"
}

export var wallet_request_status = {
    created: "Створений",
    sent: "Надісланий",
    accepted: "Прийнятий",
    transfered: "Переведений",
    completed: "Виконаний",
    cancelled: "Скасований"
}

export var status = {
    
    created: "Створено",
    waiting_for_accept1: "Замовлення створено",
    accepted1: "Прийнято",
    start_preparing_order1: "В процесі",
    order_ready1: "Готово",
    waiting_for_delivery_man1: "Назначено",
    delivery_man_accepted1: "Прийнято",
    delivery_man_coming1: "В дорозі",
    delivery_man_arrived1: "Прибув",
    picked_order1: "Здійснив підбір",
    started_for_delivery1: "Доставляється",
    arrived_at_destination1: "Доставляється",
    delivered_ordered1: "Виконано",
    assign_order_to_Delivery_man1: "Назначити кур'єра",
    no_delivery_man_found1: "Не знайдено",
    delivery_man_rejected1: "Відмовились",
    delivery_man_cancelled1: "Відмовились",
    user_cancelled1: "Скасовано користувачем",
    oredr_complete: "Замовлення виконане",
    order_delivered: "Доставлено",
    completed: "Виконано",
    rejected1: "Відмовились",
    cancelled1: "Скасовано",
    not_completed: "Не виконано",
    user_cancelled: "Користувач скасував",
    cancelled_request1: 'Не назначено',
    waiting_for_accept: "Нове замовлення створене",
    accepted: "Прийнято",
    start_preparing_order: "Почата підготовка",
    order_ready: "Замовлення готове",
    waiting_for_delivery_man: "Назначено на кур'єра",
    delivery_man_accepted: "Кур'єр прийняв замовлення",
    delivery_man_coming: "Кур'єр в дорозі",
    delivery_man_arrived: "Кур'єр прибув",
    picked_order: "Кур'єр здійснив підбір ",
    started_for_delivery: "Доставляється",
    arrived_at_destination: "Кур'єр прибув на місцепризначення",
    delivered_ordered: "Замовлення доставлено",
    assign_order_to_Delivery_man: "Назначити на кур'єра",
    rejected: "Заклад відмовився",
    cancelled: "Заклад скасував замовлення",
    no_delivery_man_found: "Кур'єр не знайдений",
    delivery_man_rejected: "Кур'єр відмовився",
    delivery_man_cancelled: "Кур'єр скасував",
    cancelled_request: 'Запит скасовано'
}


export var message = {
    country_already_exist: "Країна вже існує",
    promo_code_already_exist: "Промокод вже існує"
}